### ISSUE TITLE
Internet connection via wlan1 & 3G to wlan0

### ISSUE THREAD

**Issue by MikeOne86** [billz/raspap-webgui#1]
Are there any settings that the Internet connection via WLAN and 3G? Or is it planned?
Best Regards Mike

**Comment by webnull** [comment]
You could take a look at https://github.com/webnull/raspap-webgui
This is a refactored version of RaspAP, here when you setup 3G interface using eg. Network Manager you could use it as a internet source for your hotspot interface.

**Comment by billz** [comment]
Hi @MikeOne86, circling back to this issue as I have more time to devote to the project. There are related requests #77 and #78 to offer greater control for multiple wlan interfaces. I'm prototyping a UI that will hopefully capture much of what's needed on this front. Thanks.

**Comment by billz** [comment]
Updated the [FAQ](https://github.com/billz/raspap-webgui/wiki/FAQs#interfaces) to address this.
