### ISSUE TITLE
Add network function

### ISSUE THREAD

**Issue by sv6nob** [billz/raspap-webgui#100]
Hello,
Is there any way to add new networks on Configure client tab? I can see only saved networks with passwords, but i can't scan the available networks or add a new one manually.
Check the image https://ibb.co/kqjS1v
Thank you!

**Comment by royord** [comment]
If you just refresh the page it seems to show the other networks that are available in your area, if you've connected to all of them I do believe that you would only see the ones that you have saved.

**Comment by billz** [comment]
@sv6nob indeed @royord's comment is correct. Perhaps start a hotspot with your mobile device or try moving to an area with more wifi signals.

**Comment by kfordaccela** [comment]
@billz @sv6nob this was fixed in commit "34c22e4"

**Comment by billz** [comment]
@sv6nob closing this for now. Feel free to reopen if this isn't resolved for you, thanks.
