### ISSUE TITLE
Uninstall script

### ISSUE THREAD

**Issue by art049** [billz/raspap-webgui#107]
Hello, I want to uninstall raspap.
Do you have a script to do it cleanly ?

**Comment by SirLagz** [comment]
Not yet. It's in progress now.

**Comment by SirLagz** [comment]
This has been created now. Just needs some willing testers!

**Comment by billz** [comment]
Tested on fresh install of Jessie Lite.

Restoring backups for interfaces, hostapd, dnsmasq, dhcpcd.conf all successful.

Install directory `/etc/raspap` removed. Lighttpd directory `/var/www/html` unchanged. Should be able to fix like so:

```
sudo rm -rf "$webroot_dir"/*
```

**Comment by SirLagz** [comment]
Thanks Bill. I've updated the uninstall script.

**Comment by GunnarKammel** [comment]
how can I uninstall raspap?

**Comment by billz** [comment]
@GunnarKammel this is covered in the [FAQ](https://github.com/billz/raspap-webgui/wiki/FAQs#how-do-i-remove-raspap).

**Comment by Festerstoybox** [comment]
i have tried to uninstall using the FAQs option but i get the error saying "no such file or directory" and when i go to that folder in gui there are no files to use (installer/uninstaller).
not sure why this is happening as i installed using the guide.
