### ISSUE TITLE
Backup configuration file before installing

### ISSUE THREAD

**Issue by art049** [billz/raspap-webgui#108]
I've lost my whole pi configuration installing this.
Performing a backup of configuration files is necessary during the installation.

**Comment by SirLagz** [comment]
Which configuration file?

**Comment by art049** [comment]
/etc/network/interfaces
Hostapd configuration also.

Youre code simply overwrite without even asking.

**Comment by SirLagz** [comment]
Thanks for that. We'll look into this issue.

**Comment by SirLagz** [comment]
I've added a section into the installer to back up /etc/network/interfaces and /etc/hostapd/hostapd.conf files if found. They are moved to /etc/raspap/backups.

**Comment by art049** [comment]
Thanks for fixing that.
I think it's also needed for  /etc/dnsmasq.conf and /etc/dhcpcd.conf

**Comment by SirLagz** [comment]
Yep, newest version already has logic for those 2 files too, will be up soon
