### ISSUE TITLE
Unable to access Web Interface when Wifi + Ethernet is down

### ISSUE THREAD

**Issue by SirLagz** [billz/raspap-webgui#114]
Seems the Masquarade rule is messing things up when both eth0 and wlan0 is down.
I'm unable to access the web interface from the Pi when both are down.
Dropping the rule off brings it back up.
Probably need some logic in there to only activate the rule when RaspAP is in router mode.

**Comment by 97-109-107** [comment]
When:

- wlan0 is the interface
- wlan1 is the client
- eth0 is plugged in and connected

The interface is being broadcasted and is accesbile. The moment eth0 is unplugged, Raspap's SSID disappeards.

**Comment by SirLagz** [comment]
@97-109-107 are you referring to your own setup?
