### ISSUE TITLE
Support OrangePI

### ISSUE THREAD

**Issue by heX16** [billz/raspap-webgui#118]
I try install to OrangePi Zero.

```console
...
RaspAP Install: Installing required packages
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php5-cgi is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php5-cgi' has no installation candidate
RaspAP Install Error: Unable to install dependencies

```

**Comment by SirLagz** [comment]
What distribution are you using?

**Comment by lkoepsel** [comment]
Hi, I had the same issue using the latest version of raspbian...

**Comment by lkoepsel** [comment]
sorry, hit the wrong key: 2017-09-07-raspbian-stretch-lite. I tried to manually install, using just php-cgi. That worked, everything to install, however, I wasn't succesfull with the rest of the manual install.
Does raspap-webgui require PHP5 instead of PHP7?
Thanks,
Lief

**Comment by SirLagz** [comment]
Raspbian seems to have changed the availability of the PHP packages, we need to have a further look into this.
