### ISSUE TITLE
Installation overwrites rc.local

### ISSUE THREAD

**Issue by jadero** [billz/raspap-webgui#120]
I did an install today and realized later that my TVheadend Kodi client couldn't connect anymore to the server. A quick check showed that my custom made entries to rc.local were gone and an iptables entry was there instead which hasn't been there before I installed raspap. I couldn't find any backup file so this took me a while to get everything running again. :^(

**Comment by jadero** [comment]
Btw. I followed this tutorial for installation: [https://howtoraspberrypi.com/create-a-wi-fi-hotspot-in-less-than-10-minutes-with-pi-raspberry/](url).

**Comment by SirLagz** [comment]
There should be backups stored in /etc/raspap/backups. Did you check there?

**Comment by jadero** [comment]
After some testing I decided to remove raspap and all dependencies incl. folders in /etc. When I discovered that there was something wrong with my rc.local the raspap folder in /etc was already gone so I cannot answer your question. So I suggest that you put the backup file for rc.local right into /etc (append a suffix to it). But the question remains why there where lines removed in rc.local in the first place?

**Comment by SirLagz** [comment]
The rc.local file is updated to add in the rules for the RaspAP web GUI to act as a router.
Uninstalling RaspAP with the uninstall script would have restored the rc.local file that you had before.

**Comment by jadero** [comment]
Ok thats fine concerning the uninstallation. I didn't know that there is a script available though. But I would still consider it as a bug that custom added lines to the rc.local script are removed during installation (or that this file is replaced, whatever).

**Comment by SirLagz** [comment]
Yep, I agree. It is an issue we need to address.
