### ISSUE TITLE
Change port number

### ISSUE THREAD

**Issue by toqduj** [billz/raspap-webgui#146]
There's other competing web services running on my RPi. Any chance I can change the port number raspap works on, from 80 to something else?

**Comment by zubenubi** [comment]
Im also interested in this

**Comment by SirLagz** [comment]
You can change this manually, depending on which web server you're using. If you're using lighttpd only for RaspAP, then you can change the port lighttpd is listening on.

**Comment by billz** [comment]
Shout out to Raspberry Pie on discord. Thanks for the feedback 👍🏼

**Comment by GarethHards** [comment]
I also have raspAP on port 80 and think i should change it or should i look at changing apache2 virtual hosting ports rather instead, seems that raspAp may be the simplest way? if so how do i do this ?

**Comment by billz** [comment]
@GarethHards read the FAQ https://github.com/billz/raspap-webgui/wiki/FAQs

**Comment by GarethHards** [comment]
does raspAP actually interfere with apache2 virtual hosts on port 80 ? and occupy the same port ?
