### ISSUE TITLE
uninstall.sh not working correctly

### ISSUE THREAD

**Issue by sndpwrites** [billz/raspap-webgui#165]
### uninstall.sh did not uninstall correctly
I was having some other issues so I decided to reinstall the application. I followed your comment on this issue https://github.com/billz/raspap-webgui/issues/149 to run uninstall.sh.
However, it seems the uninstallation did not work correctly as my AP's SSID was still raspap-webgui and now I cannot connect to any wifi, even if I create a manual wpa_supplicant file.

### My environment
* Pi 3 Model B  
* Raspbian version : Stretch
* RaspAP Quick Install
* No other services running.

### Steps to reproduce
After quick installation, performing uninstall.sh does not correctly restore ALL config files. I restarted DHCP server and checked the status. It was removing my wlan0 after it tried to connect to my wifi SSID.

### Expected behaviour
I guess it should connect to wlan0 using provided settings.

### Actual behaviour
No wifi connection. My Pi's wifi is essentially useless. :(
Is there something that can be done to restore affected config files manually? Thanks.

**Comment by billz** [comment]
> my AP's SSID was still raspap-webgui 

Did you restart the hostapd service? If not, try giving it a kick. Better yet, reboot your pi. 

All relevant config files are backed up to `/etc/raspap/backups` with a datetime stamp when you run the quick installer. If in any doubt, try diff'ing the files stored here with the current config files at their destination folders.
