### ISSUE TITLE
Wi-Fi based VANET in Raspberry pi

### ISSUE THREAD

**Issue by Jafis** [billz/raspap-webgui#166]
### Wi-Fi based VANET in Raspberry pi
Hai. I have seen your Raspberry pi server setup work and i really admire your work. I am doing a vehicle to vehicle communication based collision warning system using raspberry pi and network as wi-fi. I have made the raspberry pi to work as a wi-fi server were other devices can connect to it.

My aim is to gather data like speed and position from sensors and share the data over this wi-fi server (represent subject vehicle or car)  to the clients connected to it (other vehicles like cars or trucks on the road) for using the data for calculating the possibilty of collision. I also need to get speed,postion data from the clients also and send them to the server raspberry pi for the same collision possibility calculation. (server and clients all are raspberry pi boards). So,

Q1. Is it possible the client can send data to the server and the server can send data to the client through their wireless connection? (like in wifi based media transfer apllications like 'shareit' or 'xender'). How it can be done? 

Q2. if such a data share only possible through web server then how to add and extract the data from the webserver automaticlly? is there any python code for reading or extracting the data on webpage?

Please look in to this issue.
### My environment
* Raspberry Pi hardware : Pi 3 Model B - 3 nos( 1 nos for server setup 2 nos for client set up)
* Raspbian version : Jessie
* RaspAP Quick Install or Manual setup: Not installed yet
* Other software or services running with RaspAP: DHCP Config, Deamon in server Pi

### Steps to reproduce
Extract data shared through the Wi-Fi based network among vehicles (more than 2 vehicles preferably) automaticlly without the need to login to webpage and copy paste the data manually to the collision warning algorithm ( implemented in python code).

### Expected behaviour
Vehicles are communicating each other and sharing data. No human interface in this system. The drivers only get collision warning messages. No inputs from drivers. No internet prefered
### Actual behaviour
I have developed the collision warning algorithm in python and made the raspberry pi to work as server (access point). Stuck at sharing data through wi-fi network.

**Comment by billz** [comment]
Github issues are normally not for questions, but for bug reporting or features requests.

The system you describe is feasible, but beyond the scope of this project.
