### ISSUE TITLE
Default clone folder in walktrough

### ISSUE THREAD

**Issue by mchale88** [billz/raspap-webgui#17]
Lightttpd has default webfolder /var/www/http/ not /var/www as is the place where you clone to following the walktrough

this can be resolved either with changeing the clone to folder to /var/www/html/
or change the confing in /etc/lighttpd/lighttpd.conf

on the line witch states
server.document-root        = "/var/www/html/"

to
 server.document-root        = "/var/www/"

**Comment by billz** [comment]
This should be resolved with #42. Please reopen if not, thanks.
