### ISSUE TITLE
Configure Networking is not working 

### ISSUE THREAD

**Issue by arvjsr1802** [billz/raspap-webgui#173]
Configure Networking is not working, data is saved but ethernet port value doesn't changed

**Comment by diveyez** [comment]
NONE of it is working.

**Comment by billz** [comment]
@arvjsr1802 please re-submit this with the provided issue template. You can also enable logging via the UI with Configure Client > Advanced and copy-paste the logfile output in your issue. This will greatly assist with troubleshooting. thanks
