### ISSUE TITLE
Failed to start HostAP

### ISSUE THREAD

**Issue by diveyez** [billz/raspap-webgui#177]
This entirely failed to start HostAP on boot.
I checked and this RaspAp cannot even see Hostapd when it IS already running.
Let me know when this is fixed.

**Comment by billz** [comment]
@diveyez please re-submit this with the provided issue template. You can also enable logging via the UI with Configure Client > Advanced and copy-paste the logfile output in your issue. This will greatly assist with troubleshooting. thanks
