### ISSUE TITLE
[not issue with raspap] Is there any way I can contact you(billz) privately? I would really appreciate it.

### ISSUE THREAD

**Issue by doteric** [billz/raspap-webgui#179]
Hello.

I was trying search everywhere for a way to contact you in private, but I was unsuccessful in finding anyway. Maybe you could drop some email of yours so I can write there exactly what my question/issue is?
I would really appreciate it.

Thanks,
Eric

**Comment by billz** [comment]
Our emails are in the phpDoc header of index.php 😉Feel free to get in touch

**Comment by doteric** [comment]
@billz I looked through all your other social related accounts, website and projects, but totally didn't expect that email be in the index.php file, wow.

Anyway thanks and I'll email you as soon as possible with explanation.

You can close/delete this issue if possible.
