### ISSUE TITLE
Suggestion to use 1.1.1.1 as standard DNS

### ISSUE THREAD

**Issue by jensjakob** [billz/raspap-webgui#185]
Now when an even faster DNS named 1.1.1.1 is available, we might want to use this as primary instead of 8.8.8.8 from Google. Instead 8.8.8.8 can still be kept as secondary.

**Comment by jensjakob** [comment]
https://github.com/billz/raspap-webgui/blob/f3fffd534a6063a34d54dca3a3f3848ae713a566/config/dhcpcd.conf#L17
Here, but maybe elsewhere too?

**Comment by billz** [comment]
@jensjakob great suggestion, thanks
