### ISSUE TITLE
Raspi0W : Is it possible to use both as wifi client and AP simultaneously without any external dongles, just by using the built-in Wifi?

### ISSUE THREAD

**Issue by ksmreddy** [billz/raspap-webgui#195]
### Subject of the issue
Raspi0W : Is it possible to use both as wifi client and AP simultaneously without any external dongles, just by using the built-in Wifi?

### Your environment
Raspberry Pi hardware: Pi Zero W
Raspbian version: Stretch Lite
RaspAP Quick Install
Other software or services running with RaspAP: ssh

**Comment by SirLagz** [comment]
Theoretically possible, but we haven't implemented an interface for this yet

**Comment by ksmreddy** [comment]
Thanks for the reply. Wish it would be seen one day soon.
