### ISSUE TITLE
Package 'php5-cgi' has no installation candidate

### ISSUE THREAD

**Issue by sujeet03** [billz/raspap-webgui#199]
### Your environment
* Raspberry Pi hardware (examples: Pi 3 Model B)  
* Ubuntu Mate
* RaspAP Quick Install

### Steps to reproduce
wget -q https://git.io/voEUQ -O /tmp/raspap && bash /tmp/raspap

### Expected behaviour
Install RaspAP

### Actual behaviour
Package 'php5-cgi' has no installation candidate
RaspAP Install Error: Unable to install dependencies

**Comment by billz** [comment]
Ubuntu Mate is not supported. You need to be running a version of Raspbian.

**Comment by billz** [comment]
See #124. We don't detect this OS during the install, but you can get it working by installing php7.0-cgi
