### ISSUE TITLE
Can't able start the hotspot and run

### ISSUE THREAD

**Issue by kaskou** [billz/raspap-webgui#205]
### Subject of the issue
Can't able start hotspot and run
environment
Pi 3 Model B+
Stretch
RasAP quick install

steps to reproduce:
Go to RasAP UI,  switch to configure wifi client, choose button rescan, and connect to the wifi network in list, configure hotspot, and start the hotspot

Expected behaviour:
able to create hotspot and run.
display the correct status of the hotspot and provide detail explanation if there is a issue.

Actual Behaviour:
can't able to create hotspot and run it

**Comment by billz** [comment]
Refer to #202, thanks

**Comment by billz** [comment]
Closing this as it's a duplicate of the issue referenced above.
