### ISSUE TITLE
Raspberry Pi Model B+

### ISSUE THREAD

**Issue by ShonP40** [billz/raspap-webgui#218]
### Subject of the issue
Describe your issue here: No 5 GHz and no  b/g/n/ac option

### Your environment
* Raspberry Pi 3 B+  
* Raspbian version STRETCH LITE
* RaspAP Quick Install
* Other software or services running with RaspAP: None

Can you please add 5Ghz , b/g/n and b/g/n/ac support?

**Comment by billz** [comment]
Refer to #252. Thanks
