### ISSUE TITLE
RaspAp and HostAPD config not synced and hotspot not starting

### ISSUE THREAD

**Issue by amazingalexe** [billz/raspap-webgui#222]
### Subject of the issue
The configure hotspot and actual settings for host apd are not the same and when saving settings the settings are not saved and the values set back to default. I cannot run the hotspot as raspAP says that the host apd service is not started however a check on the raspberry pi over ssh confirms that the service is running

It seems that the 2 services are not communicating with each other. 
### Your environment
* Raspberry Pi 2 B
* Raspian stretch
* Quick install
* Other software or services running with RaspAP?

### Steps to reproduce
Run the quick install on Raspian stretch (flashed By etcher)
Restart Pi and cannot find wifi hotspot so connect via IP address of pi
try to change a setting or value in the wifi hotspot config on the web client.
Also check manually that the HostAPD is running.

### Expected behavior
When Pressed save the setting, the setting should save and when pressed start hotspot, the hotspot should start

### Actual behavior
When the start hotspot button is pressed, the HostAPD is not running message is displayed(even though in the image you can see it is not) and when a setting value is changed the setting value is not saved to the hostapd config file or when the page is refreshed it returns to the default value

In this image, you can clearly see that the hostAPD service is running, but the RaspAP warning says it is not. 
![image](https://user-images.githubusercontent.com/24592144/44162298-cf2b9780-a0b7-11e8-994b-0fb10fc225b7.png)

And Here the channel of output is set to the default value of 2. I change it to 13 and it defaults back to 2 after pressing save settings. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24592144/44162626-c12a4680-a0b8-11e8-89b8-ae431e6fb37f.gif)

I am sorry if I have this completely wrong, as I am not very good with Linux. Any help would be appreciated.
Thanks in advance

**Comment by billz** [comment]
Pushed a fix. Thanks @seebz for catching this
