### ISSUE TITLE
Wireless AP on FreePBX in Raspberry Pi 3 B

### ISSUE THREAD

**Issue by gururajksa** [billz/raspap-webgui#238]
### Subject of the issue
Need Wireless AP configured on FreePBX 

### Your environment

Raspberry Pi 3 B+

### Steps to reproduce
Installed FreePBX latest from the site - http://www.raspberry-asterisk.org/downloads/

Need to enable Wireless AP on the same

### Expected behavior

Both FreePBX and Wireless AP Web portal to work on same Raspberry Pi 3 device

### Actual behaviour
Either FreePBX works or RaspAP Web Portal works. Which ever installed later takes precedence .

**Comment by billz** [comment]
This project isn't designed to work with FreePBX
