### ISSUE TITLE
Roaming

### ISSUE THREAD

**Issue by fabien321** [billz/raspap-webgui#250]
### Subject of the issue

Hello everyone,
what is the best way to roam with rasap

### Your environment
* Raspberry Pi hardware Pi 3Model B+
* Raspbian version Stretch
* RaspAP Quick Install 

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

**Comment by billz** [comment]
This topic is beyond the scope of this project. You will probably have better luck asking on raspberrypi.org/forums or raspberrypi.stackexchange.com
