### ISSUE TITLE
connecting to multiple openvpn servers - please please help!

### ISSUE THREAD

**Issue by drduker** [billz/raspap-webgui#257]
So I suck at php.

I'm trying to add a dropdown which looks inside a folder and then executes a bash script with the filename inside a folder.  I'm able to get a dropdown of the files but unable to execute script locally. I'm doing this so i can have a selection of servers to connect to with my raspberry pi.

```
<form method="post" action="">
    <select name="selected">
<?php
$files = array_diff(scandir('/home/pi/servers/VPN-TUNServers/UDP'), array('.', '..'));
foreach($files as $item){
?>
        <option value="<?php echo strtolower($item); ?>"><?php echo $item; ?></option>
<?php
        }
?>
</select>
<input type="submit" name="submit" />
```

How do I execute something like this from the same file?  I'm working the functions.php file under where the openvpn stuff is.  I'm just adding another option at the bottom of the page around line 324.

`shell_exec("sudo /home/pi/servers/connect.sh /home/pi/servers/VPN-TUNServers/UDP/$item”)`

This might be a feature request as well.  It is more of just a please help!

raspberry pi3b+

**Comment by billz** [comment]
Not an issue with RaspAP. Please try posting to https://raspberrypi.stackexchange.com/ or https://stackoverflow.com/
