### ISSUE TITLE
raspap+ppp0 as a interface to access internet .

### ISSUE THREAD

**Issue by ashwin-phadke** [billz/raspap-webgui#263]
### Subject of the issue
I have a Quectel 4G module with Sixfab 4G LTE base shield, I have raspap installed on my PC. I need to  use the ppp0 internet connection along with the raspap hotspot to work as a internet hotspot. How do I achcieve this?
I have changed the DHCP server interface to ppp0 with remaining default settings everywhere.
### Your environment
* Raspberry Pi hardware : RaspberryPi 3B+ 
* Raspbian version : Stretch
* RaspAP Quick Install or Manual setup? - Quick Install
* Other software or services running with RaspAP?
ppp0 service from sixfab.

Relevant Links below:
Sixfab 4G module : https://sixfab.com/product/quectel-ec25-mini-pcle-4glte-module/
Base hat : https://sixfab.com/product/raspberry-pi-3g-4glte-base-shield-v2/
PPP installer : https://github.com/sixfab/Sixfab_PPP_Installer
### Steps to reproduce
1) Quick Install RasAp.
2) Setup Basehat nad 4G module with RPi.
3) Install ppp0
4) Change DHCP server interface to ppp0

### Expected behaviour
1) Hotspot should be able to provide internet using ppp0 interface to connected devices.

### Actual behaviour
Shows message ,  Connected but no internet on client devices.

**Comment by billz** [comment]
Unsupported hardware and/or software.
