### ISSUE TITLE
Raspberry Pi Zero w lost connection 

### ISSUE THREAD

**Issue by CarloCattano** [billz/raspap-webgui#264]
Hotspot not created after quick install & reboot . 
* Raspberry Pi Zero w

Cant conect back to the Pi zero since it has no ethernet , and after quick install  & reboot I loose any acces to the pi so Im forced to reinstall the OS . Is there anyway to revert the installation back or just disable it from within the SD card? since I cant acces it throught SSH and I dont have a display for it...
This is quite annoying. A year ago was working out of the box ,but in the past months it has been doing this a lot

**Comment by billz** [comment]
Please refer to the [FAQ](https://github.com/billz/raspap-webgui/wiki/FAQs#pizero) re: the Pi Zero and use the project issue template, thanks.
