### ISSUE TITLE
Reserve IP adress for some mac adress

### ISSUE THREAD

**Issue by st4chuu** [billz/raspap-webgui#267]
### Subject of the issue
Try to connect ip address to mac address of clients. I've got device, which can not save static ip address. I would like to reserve some ip adress for some pool of devices, and dhcp will be always give some ip adress for mac adress.

### Your environment
* Raspberry Pi hardware (examples: Pi 3 Model B, Pi 2 Model B, Pi 1 Model B+, Pi Zero)  
Pi 3 Model B
* Raspbian version (examples: Stretch, Jessie)
Stretch
* RaspAP Quick Install or Manual setup?
 Quick Install
* Other software or services running with RaspAP?
nope

### Expected behaviour
As in Subject of the issue. Is it possible?

**Comment by billz** [comment]
It's possible, but not implemented.

DD-wrt firmware has a straightforward UI for managing DHCP static leases. Something like this could potentially be added to RaspAP in the future.


![image](https://user-images.githubusercontent.com/229399/50653734-66966780-0f3f-11e9-8a61-3980c7eab079.png)

You can reserve static IP addresses for various clients in your network by writing the reservations in `/etc/dnsmasq.conf`. The static lease takes the form `dhcp-host=<mac address>,<ip address>`.

Restart the dnsmasq service and reconnect your reserved clients.

**Comment by camilomarino** [comment]
It works perfectly. It would be nice if this was added in the webgui.
