### ISSUE TITLE
NOT Working with pi Zero W (AP+STA)active!

### ISSUE THREAD

**Issue by fu-techiot** [billz/raspap-webgui#268]
###**Hello There** @billz 
                                I have raspberry pi zero W, i have successfully installed raspAp using QUICK SETUP but the generated AP using another method is gone.

I had try manual set-up it's working fine  but whenever i'm changing the wifi settings it will not make any change on raspberry pi.
**whenever i'm trying to change the wifi netwok , it has been done on GUI but raspberry pi is still connected to previous network. there is no change.**

I'm using
Raspberry Pi Zero W rev 1.1 
Linux raspberrypi 4.14.79 (stretch)

I had already made Pi  Zero to work in AP+STA  using following simple script 
[https://github.com/lukicdarkoo/rpi-wifi/blob/master/configure](url)
 Or 
[https://blog.thewalr.us/2017/09/26/raspberry-pi-zero-w-simultaneous-ap-and-managed-mode-wifi/](url)
if i run ifconfig i'm getting this for ACCESS POINT

**Comment by linusaurus** [comment]
I have been trying to get raspAP to work on zero for weeks, and the links you give are no longer valid. How did you get raspAP to work on a pi since it need wlan0 configured first to get the AP to intall?

**Comment by billz** [comment]
@linusaurus have you checked our FAQ? There is a question that deals with this specifically. 
https://github.com/billz/raspap-webgui/wiki/FAQs#pizero

**Comment by sprokkie** [comment]
i have the same problem. i lookad at the faq, about the pi zero.
Do i have to do all the steps written down there? ( ifollowd the link)
do i have to do that before installen raspap or after installing ?

is the rasap gui working after the steps ? i love the gui.

**Comment by billz** [comment]
This may be helpful https://blog.thewalr.us/2017/09/26/raspberry-pi-zero-w-simultaneous-ap-and-managed-mode-wifi/

Will also update the FAQ accordingly.

**Comment by billz** [comment]
Managed mode AP is now [a core feature of the project](https://github.com/billz/raspap-webgui#simultaneous-ap-and-wifi-client). It was designed and tested specifically for the Pi Zero W, but will work on any RPi with onboard wireless.
