### ISSUE TITLE
Can you switch between AP and station/client mode with this?

### ISSUE THREAD

**Issue by MiloMindbender** [billz/raspap-webgui#271]
Hi, sorry to post something so simple as an issue...does this software allow you to quickly/easily switch between AP and client mode?  My application needs to be an AP when I'm using it and a client on a network for development work.

**Comment by billz** [comment]
@MiloMindbender just to clarify, I assume you mean a WiFi (rather than wired) client, correct?

**Comment by MiloMindbender** [comment]
I want to be able to run the PI as an AP, or as a client of some other AP

**Comment by billz** [comment]
I recently merged a PR that addresses this. Refer to https://github.com/billz/raspap-webgui/issues/300#issuecomment-480951529
