### ISSUE TITLE
Raspberry Pi 3B+ setup help

### ISSUE THREAD

**Issue by YeshYyyK** [billz/raspap-webgui#277]
### Subject of the issue
I setup my Pi from scratch(and installed NextCloud), then proceeded to use the quick installer script. What do I do next? There is no access point that I can see

### Your environment
* Raspberry Pi 3
* Raspbian Stretch(desktop)
* RaspAP Quick Install
* Nextcloud script(nothing after that, it is not setup completely)

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
I should see a access point right? And then be able to get to the web GUI? I want the Ethernet to be passed over to the built-in WiFi to get an access point with internet, and the web GUI

### Actual behaviour
There is no access point created, so I'm not able to really do anything

**Comment by Thaiph1308** [comment]
> Yes, I have
> […](#)
> On Sun, Jan 27, 2019 at 12:55 AM Bill Zimmerman ***@***.***> wrote: Did you set up everything in raspi-config? The wifi country setting is important. Did you reboot your Pi? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub <[#277 (comment)](https://github.com/billz/raspap-webgui/issues/277#issuecomment-457858087)>, or mute the thread

Did you fixed your isssues?

**Comment by YeshYyyK** [comment]
No, I was unable to get it working

**Comment by billz** [comment]
Please follow the steps exactly in https://github.com/billz/raspap-webgui/issues/287#issuecomment-469083944

Closing this for now. Reopen if needed, thanks.
