### ISSUE TITLE
Impossible to Manually Add a Network when in AP mode

### ISSUE THREAD

**Issue by ruky87** [billz/raspap-webgui#278]
### Impossible to Manually Add a Network when in AP mode
When in AP mode it is impossible to do a Rescan and there is no "enter SSID manually" feature.
I'm using a script to enable an AP automatically (http://www.raspberryconnect.com/network/item/330-raspberry-pi-auto-wifi-hotspot-switch-internet) when the raspy is unable to connect, then I want to use RaspAP to add a new SSID and reboot. In this way the Raspberry will connect to the desired network. The problem is that when in AP mode is impossible to do a rescan, so it will be useful a button to add a new SSID manually (or the possibility to edit a pre-existent "Default SSID" in wpa_supplicant). Also a raw editor for wpa_supplicant could be useful, if you have to do advanced configurations (like when connecting to the company network).
It could be a great idea to integrate the script from raspberryconnect.com inside RaspAP: a button to enable the service (call enable script on backend), a button to stop the service (disable script) and a checkbox for the realtime check (using cron).
I think that with these features (Auto Hotspot Switch and Manual editing of wpa_supplicant) this web gui will be a lot more useful!

### Your environment
* Raspberry Pi 3B+
* RaspAP Quick Install
* Script AP auto switch installed after RaspAP: http://www.raspberryconnect.com/network/item/330-raspberry-pi-auto-wifi-hotspot-switch-internet

### Expected behaviour
Possibility to add a new network manually

### Actual behaviour
See above

**Comment by billz** [comment]
Thanks for the feature request. I've added it to the list
