### ISSUE TITLE
make a chain

### ISSUE THREAD

**Issue by Jarwis415** [billz/raspap-webgui#281]
Is it possible to add such functionality? I have blocked most social networks in my country and it would have helped a lot, I’m even ready to pay for adding functionality

You can make a chain:
Internet => Tor
Internet => Socks/SSH
Internet = VPN => Tor
Internet = VPN => Socks/SSH
Internet = VPN = Tor => VPN
Internet = VPN = Tor => Socks/SSH
Internet = VPN = Tor = VPN => Socks/SSH

**Comment by billz** [comment]
It's possible but beyond the current scope of this project.

Suggest you take a look at PiVPN https://github.com/pivpn/pivpn
Tor is available as an apt package, eg. `sudo apt-get install tor` 
There are several good tutorials for both online.
