### ISSUE TITLE
Feature request: Add DNS settings

### ISSUE THREAD

**Issue by nlgranger** [billz/raspap-webgui#282]
Disclaimer: I'm not using this project myself but I saw someone using it.

May I sugggest adding more options related to DNS? Dnsmasq already provides multiple interesting functionalities to take advantage of. Here are some suggestions:
- activate dnsmasq caching dns server (dnsmasq.conf: port=53)
- advertise this server as default via DHCP (dnsmasq.conf: dhcp-option=6,10.0.0.1)
- add an option in GUI to override the fallback DNS (related to https://github.com/billz/raspap-webgui/issues/185 , dsnmasq.conf: no-resolv and server=9.9.9.9)
- add option for user-defined records (dnsmasq.conf: address=/hello.lan/10.0.0.1)

**Comment by billz** [comment]
Added to the future enhancements list. Thanks
