### ISSUE TITLE
More detailed instructions on setting this up?

### ISSUE THREAD

**Issue by YeshYyyK** [billz/raspap-webgui#283]
Pardon me

How exactly do I setup my Pi 3 to be a WiFi extender(using eth0/Ethernet as the source and broadcasting over its built in WiFi), using this as a frontend?

Do I follow the instructions here, then run the quick installer?: https://github.com/SurferTim/documentation/blob/6bc583965254fa292a470990c40b145f553f6b34/configuration/wireless/access-point.md#using-the-raspberry-pi-as-an-access-point-to-share-an-internet-connection

Or the initial instructions mentioned in that same post, then run the quick installer?

@billz

**Comment by billz** [comment]
Yes, you can apply @SurferTim's changes after running the Quick Installer. Thanks

**Comment by YeshYyyK** [comment]
Which one? The bottom one or the upper one? Or...both?
