### ISSUE TITLE
Wifi Hotspot / Tor Proxy / Pi-Hole

### ISSUE THREAD

**Issue by Brutalo87** [billz/raspap-webgui#286]
Hello at first Thank you for your work!
Iám new with a Raspberry and i installed Raspap un Rasbian Skretch.
After installation i have open a wifi Hotsot 
IP: 192.168.51.1
Gatway: 192.168.51.1
Submask: 255.255.255.0
Dns: 8.8.8.8

eth0 (DHCP)

I can connect to the wifi but there is no Internet.. Some Idea?

Next i try to Configure Tor Proxy i have enable it for the webif.. I tipp in:
VirtualAddrNetworkIPv4= 10.192.0.0/10
AutomapHostsSuffixes= .onion,.exit
AutomapHostsOnResolve= 1
TransPort= 9040
DNSPort= 9053
But nothing happens when i save it.. (is Tor also installed in your Paket?

After that i have install Pi-Hole for me it is a must have, the installation is completed but the webinterface i can not open maybe it is on the same port?! I also tryed www.pi.hple/admin, but nothing works...
Can you make a setting for a other port for your webinterface or make it selectable pleas :-)

Greetings Frank

**Comment by billz** [comment]
Did you consult the [FAQ](https://github.com/billz/raspap-webgui/wiki/FAQs)? There is an answer there related to integrating RaspAP with Pi-hole.

Unfortunately, I cannot help you troubleshoot RaspAP integration with TOR. The issue template has links to RPi community forums which are extremely helpful. Thanks
