### ISSUE TITLE
Latest status on a routed+NAT setup between the two wireless interfaces?

### ISSUE THREAD

**Issue by feh123** [billz/raspap-webgui#288]
### Subject
Using a Raspberry pi as a mobile hotspot where the internet is via a wifi connection and the clients connect also via wifi
### Your environment
* Raspberry Pi hardware: Pi 3 Model B  
* Raspbian version latest Stretch
* RaspAP Quick Install with bridge setup.
* Expressvpn auto runs on boot.
The above is working with a wired connection to the RPI3. This is very nice! 
### Steps to reproduce
Try the procedure in http://www.raspberryconnect.com/network/item/331-raspberry-pi-auto-wifi-hotspot-switch-direct-connection or the procedure in these forums - see "Can't seem to get this working with a RPi3 + USB WiFi for Client side #78". 
I may be misunderstanding what they want to do or making an error in following them but for me they do not work. 
### Expected behaviour
Ideally I get a fully mobile access point.
### Actual behaviour
There are many errors in the Raspap log file but the end result is a failure to start hostapd.
If any one as a procedure that would be great!

**Comment by billz** [comment]
This is not currently supported. PR's are welcome :)
