### ISSUE TITLE
No hotspot when reboot just after installation

### ISSUE THREAD

**Issue by theodugautier** [billz/raspap-webgui#296]
Hello,
I tried to install the software by following the tutorial. 
- First: update my system.
- secondly: run the command: `wget -q https://git.io/voEUQ -O /tmp/raspap && bash /tmp/raspap`
I put "y" in all the questions.
then at the end of the installation, I reboot.

but once the system is turned on again. I don't see the wifi appearing on my phone and when I try to go to address `10.3.141.1` the site is inaccessible.

Material: Rasberry Pi 3

**Comment by billz** [comment]
Refer to https://github.com/billz/raspap-webgui/issues/287#issuecomment-469083944.
Please resubmit an issue with the included template, thanks
