### ISSUE TITLE
Rasbian Skretch Hotspot doent start after Reboot

### ISSUE THREAD

**Issue by Brutalo87** [billz/raspap-webgui#299]
- Rasbian Skretch is up to Date
- Quick Insall Raspap
- Wlan Hotspot i select the Country, change SSID and so on...
- Hotspot is running...
- After Reboot i have to start Hotspot manuell...

Log (after starting manuell):

Configuration file: /etc/hostapd/hostapd.conf
Failed to create interface mon.wlan0: -95 (Operation not supported)
wlan0: interface state UNINITIALIZED->COUNTRY_UPDATE
wlan0: Could not connect to kernel driver
Using interface wlan0 with hwaddr b8:27:eb:b9:b0:10 and ssid "Ghost"
random: Cannot read from /dev/random: Resource temporarily unavailable
random: Only 0/20 bytes of strong random data available from /dev/random
random: Not enough entropy pool available for secure operations
WPA: Not enough entropy in random pool for secure operations - update keys later when the first station connects
wlan0: interface state COUNTRY_UPDATE->ENABLED
wlan0: AP-ENABLED

**Comment by billz** [comment]
Refer to this https://github.com/billz/raspap-webgui/issues/287#issuecomment-471211060. Try a reinstall with the hotfix. thanks
