### ISSUE TITLE
how would you add a reboot button?

### ISSUE THREAD

**Issue by janislejins** [billz/raspap-webgui#3]
It might be useful for the page to be able to restart the pi.
(sudo reboot)
what do you think the best way to implement this would be?

**Comment by SirLagz** [comment]
You'd need to update the sudoers file to allow www-data to execute sudo reboot, then it'd be simple to add a button to exec the command.

**Comment by billz** [comment]
Great suggestion. @zlolz has added basic system info and controls (shutdown, reboot, etc) in #9. Check it out.
