### ISSUE TITLE
RaspAP with Pi-hole not working

### ISSUE THREAD

**Issue by LiJu09** [billz/raspap-webgui#304]
### Subject of the issue
RaspAP with Pi-hole not working

### Your environment
* Raspberry Pi hardware - Pi 3 Model B+
* Raspbian version - Fresh install of Stretch Lite
* RaspAP Quick Install or Manual setup? - Quick Install
* Other software or services running with RaspAP? - Pi-hole

I trying to install Raspap and Pi-hole (twice) by this quide https://github.com/billz/raspap-webgui/wiki/FAQs#how-do-i-integrate-raspap-with-pi-hole and its not working. It looks like dhcp not working.

Please help

**Comment by billz** [comment]
Pi-hole integration is not officially supported by this project. The wiki steps were included as a convenience only. Suggest you refer to the [source](https://discourse.pi-hole.net/t/ftl-is-offline-after-update-to-4-0/11673/39) and post a follow up in that forum.
