### ISSUE TITLE
[Feature request] Start hostapd automatically

### ISSUE THREAD

**Issue by pcs3rd** [billz/raspap-webgui#305]
One thing I noticed while configuring Raspap is that once I reboot, hostapd doesn't start at boot.
**Could** a option to start raspap at boot be added?

**Comment by mrevilme** [comment]
I had a similair issue but it was not that hostapd doesnt start automatically but more that wpasupplicat takes control of the device when booting.

Solution edit /etc/network/interfaces and set;

`iface wlan1 inet manual
    nohook wpa_supplicant`

**Comment by billz** [comment]
@pcs3rd please resubmit with the provided issue template, thanks
