### ISSUE TITLE
Little problem to acces motion eye :

### ISSUE THREAD

**Issue by Nico53220** [billz/raspap-webgui#309]
Hey thre ! 
First of all what a nice app ! 

So there are the basics of my project : 
  - I have my "global network" at home with DHCP adress between 192.168.1.10 and 
    192.168.1.255.
  - The Pi adress where raspap is installed is 192.168.1.31.
    I can connect myself to the raspap menu with this adress (http://192.168.1.31:80) wherever 
    I am on my "global network". 
    When i'm on my Pi i can connect myself to the menu with this adress http://10.3.141.1.
  - I have an other Pi Zero W with MotionEyeOS (it s a webcam server). This Pi0 is connected to 
    the raspap network. So on the Raspap network the MotionEyeOS interface is on this adress : 
    http://10.3.141.205 or http://10.3.141.1:80.

In this way everything is working perfectly. But my problem is the following, how can I acces to my MotionEyeOS server, when i'm on my global network ? 
Because when i'm on my global network and I'm searching this page "http://10.141.1:80" or "http://10.141.1.205",  nothing is found.

Thank you for your help,
Nico from France :-)

**Comment by billz** [comment]
Start by enabling packet forwarding for IPv4 on the Pi0 by adding `net.ipv4.ip_forward=1` to `/etc/sysctl.conf` (usually this line exists, you only need to uncomment it). You will then need to define a static route between the Pi0 and the Pi hosting RaspAP. View the current routing table with `ip route list`. Based on your description above, I could suggest creating a new route with:

`sudo ip route add 10.3.141.1/24 via 192.168.1.31 dev eth0 proto static`

... substituting `eth0` for your interface. Execute `ip route list` again to confirm the route was established. Try accessing the Pi0 from your 192.168.1.* network.

I can't promise this will solve your networking issue but hopefully it will put you on the right track. Best of luck.
