### ISSUE TITLE
Rasp AP SSID not broadcasting

### ISSUE THREAD

**Issue by halfajobj** [billz/raspap-webgui#313]
Hi there I installed this raspap thinking i would be easier the manualy installing it in stretch. i changed the ssid name gave myself a static Ip Address and enabled access point client mode to work when connected to internet. i rebooted the system and the access point dissapeared and would not re-appear.  when i hover over the wifi icon on the desktop gui i get Wlan0 not asscociated. I have previously followed this guide when creating it manualy and have never had an issue.  https://github.com/raspberrypi/documentation/blob/763fdfec2cf6857828a41be70a008e1a487aed3e/configuration/wireless/access-point.md any surgestions

pi@raspberrypi:~ $ sudo service dhcpcd restart
Warning: dhcpcd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
pi@raspberrypi:~ $ 

pi@raspberrypi:~ $ sudo service dnsmasq status
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-04-11 23:27:00 BST; 5min ago
  Process: 565 ExecStartPost=/etc/init.d/dnsmasq systemd-start-resolvconf (code=exited, status=0/SUCCESS)
  Process: 551 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=0/SUCCESS)
  Process: 501 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
 Main PID: 564 (dnsmasq)
   CGroup: /system.slice/dnsmasq.service
           └─564 /usr/sbin/dnsmasq -x /run/dnsmasq/dnsmasq.pid -u dnsmasq -r /run/dnsmasq/resolv.conf -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service --trust-anchor=.,19036,8,2,49aac11d7b6f6446702e54a160737160

Apr 11 23:26:59 raspberrypi systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Apr 11 23:27:00 raspberrypi dnsmasq[501]: dnsmasq: syntax check OK.
Apr 11 23:27:00 raspberrypi dnsmasq[564]: started, version 2.76 cachesize 150
Apr 11 23:27:00 raspberrypi dnsmasq[564]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
Apr 11 23:27:00 raspberrypi dnsmasq[564]: warning: interface wlan0 does not currently exist
Apr 11 23:27:00 raspberrypi dnsmasq-dhcp[564]: DHCP, IP range 192.168.1.145 -- 192.168.1.150, lease time 1h
Apr 11 23:27:00 raspberrypi dnsmasq[564]: read /etc/hosts - 5 addresses
Apr 11 23:27:00 raspberrypi dnsmasq[564]: no servers found in /run/dnsmasq/resolv.conf, will retry
Apr 11 23:27:00 raspberrypi dnsmasq[565]: Too few arguments.
Apr 11 23:27:00 raspberrypi systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.
lines 1-20/20 (END)

 dhcpcd.service - dhcpcd on all interfaces
   Loaded: loaded (/lib/systemd/system/dhcpcd.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/dhcpcd.service.d
           └─wait.conf
   Active: active (running) since Thu 2019-04-11 23:33:54 BST; 25s ago
  Process: 2883 ExecStop=/sbin/dhcpcd -x (code=exited, status=0/SUCCESS)
  Process: 2909 ExecStart=/usr/lib/dhcpcd5/dhcpcd -q -w (code=exited, status=0/SUCCESS)
 Main PID: 2965 (dhcpcd)
   CGroup: /system.slice/dhcpcd.service
           ├─2924 wpa_supplicant -B -c/etc/wpa_supplicant/wpa_supplicant.conf -iwlan0 -Dnl80211,wext
           └─2965 /sbin/dhcpcd -q -w

Apr 11 23:33:49 raspberrypi dhcpcd[2909]: eth0: probing address 192.168.1.145/24
Apr 11 23:33:49 raspberrypi dhcpcd[2909]: eth0: soliciting an IPv6 router
Apr 11 23:33:49 raspberrypi dhcpcd[2909]: eth0: Router Advertisement from fe80::5a90:43ff:feba:5c6f
Apr 11 23:33:49 raspberrypi dhcpcd[2909]: eth0: adding address fdaa:bbcc:ddee:0:ba27:ebff:fe96:b04e/64
Apr 11 23:33:49 raspberrypi dhcpcd[2909]: eth0: adding address 2a00:23c4:851c:2100:ba27:ebff:fe96:b04e/64
Apr 11 23:33:49 raspberrypi dhcpcd[2909]: eth0: requesting DHCPv6 information
Apr 11 23:33:54 raspberrypi dhcpcd[2909]: eth0: leased 192.168.1.145 for 86400 seconds
Apr 11 23:33:54 raspberrypi dhcpcd[2909]: eth0: adding route to 192.168.1.0/24
Apr 11 23:33:54 raspberrypi dhcpcd[2909]: eth0: adding default route via 192.168.1.254
Apr 11 23:33:54 raspberrypi systemd[1]: Started dhcpcd on all interfaces.
Warning: dhcpcd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
pi@raspberrypi:~ $

**Comment by billz** [comment]
Resubmit with the provided issue template, thanks.
