### ISSUE TITLE
wlan1 Not Working for Managed Mode + AP

### ISSUE THREAD

**Issue by arrmo** [billz/raspap-webgui#323]
### Subject of the issue
I have made the changes as per the FAQ (https://github.com/billz/raspap-webgui/wiki/FAQs#interfaces), to try to move from wlan0 (internal), to wlan1 (USB). But after these changes, and even a reboot ... hostapd doesn't seem to come up (and uap0 is not created, or at least not consistently).

### Your environment
* Raspberry Pi hardware (examples: Pi 3 Model B, Pi Zero W)  
Pi 3 Model 3B+

* Raspbian version (examples: Stretch Lite, Stretch Desktop)
Stretch Desktop

* Followed the project prerequisites? (Y/N)
Y

* Checked the project FAQ? (Y/N)
Yes, configured as noted above.

* RaspAP Quick Install or Manual setup?
Quick Install

* Using default configuration? (Y/N)
N

* Simultaneous AP and managed mode? (Y/N)
Y

* Other software or services running with RaspAP?
N

### Steps to reproduce
Made the changes as noted above (wlan0 => wlan1), but it doesn't seem to be working.

### Expected behavior
Network should come up, WiFi client (this part is OK), also AP.

### Actual behavior
Seems to fail on the hostapd side of things. Wondering if some of the info here points to the root cause (https://wiki.archlinux.org/index.php/software_access_point)
=> I did check iw list, and AP is in the USB based WiFi adapter, but ...
=> looking at the "valid interface combinations" ... is there specific capability that is needed? Thinking this may be the issue ... thoughts?

Thanks!

**Comment by billz** [comment]
Good catch. This is a departure from the default configuration but is a good case to support. It hinges on `servicestart.sh` (a recent addition to the project) which is currently restricted to `wlan0` in the default config:

https://github.com/billz/raspap-webgui/blob/5ef015ee880a4b576e02ab97f7a6a7bf0e6dd76e/installers/servicestart.sh#L42

The script should be updated to take the wifi client interface as a parameter. An additional piece will be to persist `RASPI_WIFI_CLIENT_INTERFACE` to `/etc/raspap/hostapd.ini`. This is needed by the RaspAP service to enable the Wifi client AP on boot.
