### ISSUE TITLE
configure_client.php not showing authentication protocols (includes solution)

### ISSUE THREAD

**Issue by furest** [billz/raspap-webgui#326]
### Subject of the issue
The DisplayWPAConfig method has a bug where the protocol of discovered wifi networks isn't shown on the page

### Your environment
(doesn't matter, the problem is located in the PHP code)

### Steps to reproduce
1. Consult the list of discovered wifi networks
2. Realize the "Security" field is empty

### Expected behavior
The security field should show the WPA or WPA2.

### Actual behavior
The security fiels is empty.

###Solution
In the file includes/configure_client.php:
Lines 140-143 shoud be put after line 159. 
Currently the test made to check whether the wifi network is already known or not is based on the presence of the index in the $networks array. 
However at  line 142 the array is created to memorize the RSSI of the network.
Hence the network will always be considered as "saved" as the index will always exist.
The original file with the solution are both in the archive below.

Please excuse my basic and probably incomplete report. I haven't got much time today but still wanted to let you know about this.

[solution.tar.gz](https://github.com/billz/raspap-webgui/files/3144646/solution.tar.gz)

**Comment by billz** [comment]
Good catch. Thanks
