### ISSUE TITLE
How to get wirelles mode b only?

### ISSUE THREAD

**Issue by bm0383** [billz/raspap-webgui#328]
### Cant set wireless mode b only
Im doing a little comparison in bandwith with iperf on modes b/g/n. And i cant get just mode b to work. Currently i have:

Mode G is default

mode N i get with wireless mode = n and security-> encryption type = CCMP (https://github.com/billz/raspap-webgui/issues/291)

 But i cant get mode B to work.  In WifiScanner aplication and windows properties it just show g when there should  b.

also...Is there any more tricks so i can get larger bandwith? I will try also different security types...

### Your environment
* Raspberry Pi 3b+
* Raspbian Stretch Desktop
* Followed the project prerequisites? Y
* Checked the project FAQ? Y
* RaspAP Quick Install

**Comment by billz** [comment]
Saving hostapd settings with wireless mode B selected will update hostapd.conf with `hw_mode=b`. For 802.11b you should only configure channel 1,6 or 11. However, what you observe practically will depend on several factors. The WiFi hardware driver, the wireless chipset or both may ignore your hostapd settings. 

![image](https://user-images.githubusercontent.com/229399/57878393-38446500-781a-11e9-8ea6-f77e46a3ee73.png)

Software tools reporting operational modes of WiFi hardware may also report falsely. 

For example, on a Pi Zero W configured with wireless mode B, the output of `iwlist scanning` shows that the AP has 

```
wlan0     Scan completed :
          Cell 01 - Address: 62:A0:78:D0:80:72
                    Channel:6
                    Frequency:2.437 GHz (Channel 6)
                    Quality=67/70  Signal level=-43 dBm  
                    Encryption key:on
                    ESSID:"Freebox-router"
                    Bit Rates:1 Mb/s; 2 Mb/s; 5.5 Mb/s; 11 Mb/s; 22 Mb/s
                              6 Mb/s; 9 Mb/s; 12 Mb/s
                    Bit Rates:18 Mb/s; 24 Mb/s; 36 Mb/s; 48 Mb/s; 54 Mb/s
                    Mode:Master
```

 

Refer to the hostapd documentation https://wireless.wiki.kernel.org/en/users/documentation/hostapd
