### ISSUE TITLE
uninstall script does not remove packages

### ISSUE THREAD

**Issue by ybornat** [billz/raspap-webgui#336]
### Subject of the issue
The install script (raspap) downloaded and installed debian/rapbian packets. The uninstall script did not get rid of them.

### Your environment
* Raspberry Pi hardware : Pi 3B
* Raspbian version : Stretch Lite
* Followed the project prerequisites? (Y)
* Checked the project FAQ? (Y)
* RaspAP Quick Install
* Using default configuration? (Y)
* Simultaneous AP and managed mode? not relevent
* Other software or services running with RaspAP? yes but not related

### Steps to reproduce
quick install on a fresh raspbian, then unsintall using the provided script

### Expected behavior
I expect all packets required and installed by raspap to be removed from the system

### Actual behavior
these packets are still on the system

**Comment by billz** [comment]
Added a prompt to optionally remove packages installed by RaspAP.
A user could install these packages separately (ie., outside of this project) so giving them the option to uninstall is the right approach here.
