### ISSUE TITLE
RaspAP not compatible with Raspbian Buster

### ISSUE THREAD

**Issue by CorentinDy** [billz/raspap-webgui#337]
### Subject of the issue

Hi, i've just install raspbian Buster (which is now stable released on rpi), but some packages are no more supported in this release; like "php5-cgi" and maybe some others but can't test .

I know Buster has been released only this morning, but do you have a quick fix for now ? (I didn't tried manual install, but i will if there is no quick fix)
And maybe for later a new release with Buster support ?

I hope there is no big breaking things

### Your environment
* Raspberry Pi hardware (Pi 1)  
* Raspbian version (Buster Lite)
* Followed the project prerequisites? (Y)
* Checked the project FAQ? (Y)
* RaspAP Quick Install or Manual setup? Quick Install
* Using default configuration? (Y)
* Other software or services running with RaspAP? No

**Comment by CorentinDy** [comment]
As your documentation is really well written, manual installation work perfectly.

**Comment by billz** [comment]
Pushed a fix to the Quick Installer to detect Buster. 

As you noted, this was released only this morning. A more complete testing cycle will be performed with Buster shortly. Thanks

**Comment by ldinatale** [comment]
Hello, I just installed RaspAP on Raspbian Buster (10) performing a semi-manual installation. I downloaded the 'raspapcommon.sh' file and changed the required package php7.0-cgi in php7.1-cgi and then the installation goes well.

**Comment by billz** [comment]
Updated installer & uninstaller for php7.1-cgi (Buster). Thanks
