### ISSUE TITLE
Force 2.4 for access point?

### ISSUE THREAD

**Issue by jamenlang** [billz/raspap-webgui#338]
I've got some wifi clients that can't connect to 5ghz anything. Older kindle fires.

is there a way to force apd to 2.4ghz? i thought that switching to g only would do the trick but I still can't see the SSID after rebooting.

### Before submitting an issue

Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues. 

### Subject of the issue
Describe your issue here.

### Your environment
* Raspberry Pi hardware (examples: Pi 3 Model B, Pi Zero W)  
* Raspbian version (examples: Stretch Lite, Stretch Desktop)
* Followed the project prerequisites? (Y/N)
* Checked the project FAQ? (Y/N)
* RaspAP Quick Install or Manual setup?
* Using default configuration? (Y/N)
* Simultaneous AP and managed mode? (Y/N)
* Other software or services running with RaspAP?

### Steps to reproduce
Tell us how to reproduce this issue. Provide as much detailed information as possible.

### Expected behavior
Tell us what should happen.

### Actual behavior
Tell us what you observed instead.

**Comment by billz** [comment]
The default configuration uses wireless mode g (2.4 GHz) so there is nothing to force. 
Try changing security type to WPA2 and encryption to CCMP. Restart your hotspot.

Closing as this is not a troubleshooting forum.
