### ISSUE TITLE
Compatibility with RPI 4B

### ISSUE THREAD

**Issue by oelegeirnaert** [billz/raspap-webgui#339]
Hello,

Has someone already tried the RaspAP with the new RPI 4B and the new Buster?
Are there any compatibility issues?

Kind Regards,
Oele Geirnaert

**Comment by billz** [comment]
Per the readme, the project has been updated for Buster compatibility. I do not yet have an RPi 4B for testing. Until then, I look forward to input from the RaspAP community on possible hardware compatibility issues.
