### ISSUE TITLE
Access webgui after Simultaneous AP and Wifi client ENABLED

### ISSUE THREAD

**Issue by blablaaddi** [billz/raspap-webgui#340]
Hi running RaspAP on a ZeroW, turned on Simultaneous AP and Wifi client to access via VNC. My problem is now to access the webgui as it's IP 10.3.141.1 is not valid anymore.

**Comment by billz** [comment]
Refer to https://www.raspberrypi.org/documentation/remote-access/ip-address.md

Usually mDNS will resolve your Pi's IP address as `raspberrypi.local` (assuming you're using the default hostname). In practice, this can take a few minutes when switching from the default `wlan0` config to WiFi client AP mode. 

Alternatively, check your router's DHCP leases or use `nmap` to discover the Pi's IP address.
