### ISSUE TITLE
Can't get a sudo command to work form PHP page

### ISSUE THREAD

**Issue by robboz4** [billz/raspap-webgui#349]
### Before submitting an issue

Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues. 

### Subject of the issue
Can't get a sudo command to run from php in www/html directory.

### Your environment
* Raspberry Pi hardware (examples: Pi 3 Model B, Pi Zero W)  Model B
* Raspbian version (examples: Stretch Lite, Stretch Desktop) Raspbian GNU/Linux 8 (jessie)* Followed the project prerequisites? (Y/N) Y
* Checked the project FAQ? (Y/N) Y
* RaspAP Quick Install or Manual setup? One line wget from your web page
* Using default configuration? (Y/N)Y
* Simultaneous AP and managed mode? (Y/N)
* Other software or services running with RaspAP? No just basic software, your software, the My_Halloween.py script.

### Steps to reproduce
I have a working php page that has two sudo commands executed from a button. The script worked fine before installing your software under the Apache web server. I installed the file in the var/www/html directory and it seems to work displaying the information I want. The file executes a command to look for either "oxmplayer" or "My_Halloween.py"  script running. If it detects these it changes the wording and color of  two  buttons.  These buttons should allow the omxplayer or the script if they are running to be stopped, and start them if they are not. The buttons don't work except in changing color. But there is a third button called shutdown - it executes "sudo shutdown -h now" and it works. The error code from the "sudo kill -9  {pid number} is 1.

The installation went with out a problem as far as I can tell and the software works great.

### Expected behavior
The commands should work like the sudo shutdown command. I had to set the www-data Apache permissions to pi for it previously, so I'm assuming I have a permissions error somewhere, but as shutdown works I'm not sure.

### Actual behavior
exit is 1 for the kill command

**Comment by billz** [comment]
This project does not change existing settings in `/etc/sudoers`. Check your permissions with `visudo`.
