### ISSUE TITLE
raspap not starting anymore

### ISSUE THREAD

**Issue by qwertyFrank** [billz/raspap-webgui#353]
Hi,

All work find.

But I deactivated support of WiFi Client and logging via web-GUI and rebooting the system. Since that not any more possible to accesss to raspap. No AP anymore visible via WiFi.

How to proceed?

Any possibilty to get access to raspap GUI via console (not via browser)?

Thanks
Frank

**Comment by billz** [comment]
Please resubmit with the provided issue template.
