### ISSUE TITLE
special characters in Password

### ISSUE THREAD

**Issue by asterix4you** [billz/raspap-webgui#354]
Hi,
in the security module of the config hotspot tab the PSK field does not accept special characters like $, %, &, ,etc. For example:
Admin$12345 changes to Admin
Max.

**Comment by billz** [comment]
The wpa_passphrase (PSK) field accepts all characters. Check the contents of `hostapd.conf` where the value is stored.

This value, like all user string inputs, is displayed in the form with `htmlspecialchars()`. The project has standardized on this approach.
