### ISSUE TITLE
IPv6 client route

### ISSUE THREAD

**Issue by Darkw00** [billz/raspap-webgui#359]
### Subject of the issue
I have a question. I managed to get wlan1 to work instead of eth0. Everything is ok as long as the wlan1 (client) is connected to network that is providing ipv4. The problem occurs when i connect to network that only provides ipv6. How do i route? share internet with wlan0 hotspot than? What do i need to change or enable?

### Your environment
* Raspberry Pi hardware  Pi 3 Model B
* Raspbian version Stretch Desktop
* Followed the project prerequisites? (Y)
* Checked the project FAQ? (Y)
* RaspAP Quick Install and Manual wlan1 setup
* Using default configuration? (Y)
* Simultaneous AP and managed mode? (N)
* Other software or services running with RaspAP? (No)

### Steps to reproduce
I followed this guide:
https://github.com/billz/raspap-webgui/issues/198#issuecomment-403086854
And to get internet to work i had to remove line "static routers" in /etc/dhcpcd.conf

### Expected behavior
Internet connection should pass through wlan0.

### Actual behavior
I can connect and it works with ipv4 but with ipv6 there is "no internet access".

**Comment by PidgeyBE** [comment]
How is this issue resolved? How is ipv6 handled? Do we need to enable ipv6 forwarding as well? Or disable ipv6 on our raspberry pi?
