### ISSUE TITLE
Invalid CSRF TOKEN

### ISSUE THREAD

**Issue by JustACodingFox** [billz/raspap-webgui#377]
### Subject of the issue
If I press the "stop wlan0" button or if I try to connect to a wifi, I get the error "Invalid CSRF TOKEN". 

### Your environment
* Raspberry Pi hardware:  Pi Zero W
* Raspbian version: Raspbian GNU/Linux 10 (buster)
* Followed the project prerequisites? Yes
* Checked the project FAQ? Yes
* RaspAP Quick Install or Manual setup? Tried both. Resetted the system in between.
* Using default configuration? Yes
* Simultaneous AP and managed mode? I want to but i can´t.
* Other software or services running with RaspAP? Not that I know of

### Steps to reproduce
Follow installation instructions and try to stop wlan or to connect to a wifi.

### Expected behavior
It should connect to a wifi or stop wlan.

### Actual behavior
I get forwarded to a white website with the sentence "invalid csrf token"

**Comment by JustACodingFox** [comment]
I installed rasbian buster lite fresh and updated + upgraded the system. After that I selected my locale and installed per quick install but the error still persist.

**Comment by billz** [comment]
Merged PR #376. Could be related to what you reported, although I was unable to repro this on a Pi Zero W. Please update your install and try again, thanks

**Comment by Slluxx** [comment]
still an issue. Rasp 3b+ when starting the client interface
