### ISSUE TITLE
RaspAp as Monitor Only

### ISSUE THREAD

**Issue by carlosanunes** [billz/raspap-webgui#378]
### Subject of the issue
For my purposes ( https://github.com/billz/raspap-webgui/issues/335#issuecomment-503999343 ), I used a different approach than RaspAp supports ( https://raspberrypi.stackexchange.com/questions/95072/access-point-as-wifi-router-repeater-with-additional-wifi-dongle ), but I still desire a simple and good web GUI to monitor my local network and client connection.

My suggestion for an enhancement, assuming there is no current easy way for this, would be to have an configuration option to use RaspAp only as a monitor, and not having it actually change any system settings and/or not having RaspAp expecting it to be possible.

### Your environment
* Pi Zero W
* Stretch Lite
* Checked the project FAQ? Y

**Comment by billz** [comment]
There's a valid use case for this and it's trivial to implement. 

Simplest solution is to add a `RASPI_MONITOR_ENABLED` option to config.php, defaulting to false. Setting to true will suppress the save function for settings.
