### ISSUE TITLE
Extensible Device Configuration

### ISSUE THREAD

**Issue by chintal** [billz/raspap-webgui#381]
**Network Proxy Configuration isn't handled**
RASPAP doesn't currently provide any infrastructure to deal with network proxy configurations. I know there isn't a one-size-fits-all solution for this, but it might be possible to provide just enough to support custom applications. For reference, what I am using RASPAP for is similar to what is described in #156

**The ideal situation**

The wegbui allows the users to set a HTTP proxy, including username, password, host, port, etc. Raspap goes and sets the proxy wherever a typical installation requires it. In the case of debian based distributions like raspbian, this will be in /etc/apt/conf.d  and as HTTP_PROXY environment variables. However, this is likely to be very messy and will depend heavily on the distribution and the application.

**A less specific and more DIY solution (suggested)**

Allow raspap to be installed and configured such that the person installing RASPAP can specify a set of environment variables that can be provided from the webui. Minimally, don't actually create environment variables but dump this configuration into a file readily readable by userspace applications (perhaps locked to a specific UID/GID), and let the developer of custom applications figure out how to access and apply this information wherever necessary. Don't bother with any kind of validation of the provided data or allow the validation to be configured in the installation and leave it up to the application developer to figure out what configuration parameters are necessary and if validation is needed. An optional validation hook might be nice. By keeping it a generic environment configuration scheme, it could be used for any specialized configuration needed for headless and signage-like RPis.

**Alternatives**

Unfortunately, short of pulling out the SD card and manually writing to it's filesystem, there doesn't seem to be a good way to handle this problem on a decidedly headless or signage only raspberry pi. Any specialized solution that solves the problem will need to replicate large portions of raspap, and proxy configuration is typically considered a network configuration step and does belong naturally within it.

**Additional context**

Applies to applications which use raspap-webgui for dealing with device configuration (in the field) for  headless and signage-type RPi applications, ie, no user input (mouse, keyboard, touchscreen) is possible on the device directly.

**Comment by billz** [comment]
As discussed in the PR, it's unclear if this fits the scope of the project. I would encourage you to fork the project and develop a feature along these lines, though. Thanks
