### ISSUE TITLE
unable to access the GUI

### ISSUE THREAD

**Issue by heatpj** [billz/raspap-webgui#391]
Hello, i have recently setup raspap and the WiFi connection is acting as it should.

The only issue is that the router's user interface is unable to connect and allow for editing.  
i have pi-hole running on another pi, but it is disabled.
devices connected to it, along with the pi itself cannot access the GUI
This problem is truly random, hope for any insight you may have on it!

![image](https://user-images.githubusercontent.com/54660858/63918090-00001580-ca0a-11e9-931f-6e8c698771df.png)

**Comment by billz** [comment]
Please resubmit with the provided issue template, thanks
