### ISSUE TITLE
dns_probe_finished_bad_config when using with VPN

### ISSUE THREAD

**Issue by arahasya** [billz/raspap-webgui#395]
Hi. I followed the installation guide and the access point works perfectly. Now I wan to use a VPN for the access point. I have installed NordVPN linux client. When I connect to a vpn server the internet works only on the raspberry pi and not on devices connected through wi-fi. It shows 
dns_probe_finished_bad_config 
error.
Please guide how to resolve this conflict. Thank you!

**Comment by billz** [comment]
Please read [this](https://github.com/billz/raspap-webgui/wiki/Reporting-issues), thanks.
