### ISSUE TITLE
Do not request PSK for open networks

### ISSUE THREAD

**Issue by ddieffen** [billz/raspap-webgui#4]
From the Configure client page,

When I'm trying to connect to an open network (without any password) the "Save" button is disabled for that network. I think we should allow an option, or at least recognize that open networks do not require passwords to be saved.

Maybe also it would be nice to add a field for identity="" and password in case the WiFi network requires authentication

**Comment by jrmhaig** [comment]
It is a bit rough at the moment but if you want you could have a look at this - https://github.com/jrmhaig/raspap-webgui/tree/client - to see if it works for you. I will probably tidy it up (a lot!) before making a pull request but I would be interested to hear any feedback.
