### ISSUE TITLE
It would like to run it in "bridge mode"

### ISSUE THREAD

**Issue by jmar83** [billz/raspap-webgui#400]
It would like to run it in "bridge mode" (so no dhcp server on raspi and no different subnets)

Or is that already possible? Can't see any options for that...

Thank you for your feedbacks.

Best regards,
Jan

**Comment by jmar83** [comment]
Still not available in GUI mode?
-> https://github.com/billz/raspap-webgui/issues/379

Regards, Jan

**Comment by billz** [comment]
Duplicate of #379

**Comment by jmar83** [comment]
ok
