### ISSUE TITLE
Isolating access to devices in network

### ISSUE THREAD

**Issue by L1qu1d1c3** [billz/raspap-webgui#402]
**Is your feature request related to a problem? Please describe.**
I’d like to know if its possible to have the AP in an “isolated” mode, something like a “guest” home wifi - because I want people that connect to the RPI AP to not see any other devices in my other ip subnets, like 192.168.1.*

**Describe the solution you'd like**
Be able to have the AP in an “Isolated” mode

**Comment by billz** [comment]
This is discussed in #275.

**Comment by L1qu1d1c3** [comment]
Yes, it may be, but this implies my manual setup, something i’m not an expert on, hence my feature request if webgui could let you do it.Thanks!
