### ISSUE TITLE
端口被占用了，raspap-webgui无法访问

### ISSUE THREAD

**Issue by wangkai88** [billz/raspap-webgui#404]
你好，我的树莓派已经安装宝塔了，然后安装raspap-webgui访问不了，80端口被占用了，不知道raspap-webgui的访问端口在哪里修改

**Comment by BANKA2017** [comment]
[https://github.com/billz/raspap-webgui/issues/247#issuecomment-429638686](https://github.com/billz/raspap-webgui/issues/247#issuecomment-429638686)

**Comment by billz** [comment]
@BANKA2017 thanks, you beat me to it 😉I'll add this to the FAQ

**Comment by billz** [comment]
FAQ updated, thanks
