### ISSUE TITLE
Dnsmasq configuration fails to be updated after adding DHCP static lease

### ISSUE THREAD

**Issue by koenvervloesem** [billz/raspap-webgui#407]
**Describe the bug**
Adding a DHCP static lease doesn't work.

**Your environment**
* Raspberry Pi 4 Model B
* Raspbian Buster Lite
* Followed the project prerequisites? Y
* Checked the project FAQ? Y
* RaspAP Quick Install
* Using default configuration? Y
* Simultaneous AP and managed mode? N
* Onboard wireless chipset
* Other software or services running with RaspAP? N

**Steps to reproduce**
Go to DHCP static leases. Add MAC address 58:48:22:ed:59:57a and IP address 10.3.141.220. Click Add and save settings.

**Expected behavior**
A DHCP static lease has been added.

**Actual behavior**
No DHCP static lease has been added. I get the error message "Dnsmasq configuration failed to be updated."

**Additional context**
I tried a couple of IP addresses, both inside and outside the DHCP range.

**Comment by billz** [comment]
I'm able to repo this. Pushing a fix
