### ISSUE TITLE
Kernel Panic with default install

### ISSUE THREAD

**Issue by HikariNoKitsune** [billz/raspap-webgui#408]
Not sure how I can exactly report this, as it just doesn't work.

Using a Pi 3 B+ and following the directions, everything works at first. I can connect to the WebGUI and browse around things. 

Issue happens once anything tries to connect to it. The Pi Kernel Panics. That's it. I have no way (to my knowledge) to get some sort of log for the panic... unless someone knows how and can direct me. But basically this is useless to me currently...

Using Raspbian Buster Lite 2019-09-26 with Kernel Version 4.19. 

I've been desperately trying to get some sort of passthrough AP set up with the pi here at where I work... we have Cisco Routers, and they apparently have some radio chip that an ESP isn't compatible with... our company bought a 3D printer, and it uses this ESP to communicate over WiFi. So since the Cisco routers aren't able to maintain the connection for the ESP, we were going to set up a cheap alternative temporarily until the next budget is approved... We were hoping this would finally be what we were looking for after having tried countless tutorials online... but just nothing works...

Before someone asks: 
No, we can not hook the printer up via Ethernet. It only has WiFi. No we can not use the USB and just connect it to a laptop/computer, as the Group Policy forces a computer to log off after 10 minutes of inactivity. No we can not use the Pi as an Octoprint Server, because the printer has a Duet WiFi, so it already has a built in WebGUI Server, so using Octoprint is redundant. 

If anyone knows of a reason why this software/whatever causes a kernel panic when something connects, I'd love to hear it...

**Comment by billz** [comment]
Resubmit with the provided issue template, thanks
