### ISSUE TITLE
树莓派里4b连接到wifi后，树莓派4b内部无法上网

### ISSUE THREAD

**Issue by wangkai88** [billz/raspap-webgui#411]
树莓派里4b连接到wifi后，树莓派4b内部无法上网，但是电脑连接到树莓派4b的wifi热点后，电脑可以上网，树莓派4b确不能上网

**Comment by billz** [comment]
Did you follow the [project prerequisites](https://github.com/billz/raspap-webgui#prerequisites) before installing RaspAP? If your issue persists, please resubmit with the provided template. Thanks
