### ISSUE TITLE
Client list table display incorrect

### ISSUE THREAD

**Issue by cwxyz007** [billz/raspap-webgui#412]
**Describe the bug**
Client list table display incorrect

**Your environment**
* Raspberry Pi hardware (examples: Pi 4)  
* Raspbian version (Buster Lite)
* Followed the project prerequisites? (Y)
* Checked the project FAQ? (Y)
* RaspAP Quick Install or Manual setup? Quick Install
* Using default configuration? (Y)
* Simultaneous AP and managed mode? (Y)
* Onboard wireless chipset or external adapter? Onboard wireless chipset
* Other software or services running with RaspAP? No

**Steps to reproduce**
1. Connect raspi-webgui with wifi
2. Login into dashboard with default username and password
3. Click ` Configure DHCP Server`
4. Click `Client list`

**Expected behavior**
Show the information of client in one row

**Actual behavior**
All client information show in one column

**Screenshots**
![image](https://user-images.githubusercontent.com/14226737/66713013-c0359780-edd7-11e9-9500-2cecf050cd4b.png)

**Comment by glaszig** [comment]
thanks for the report. that gets collaterally fixed when #410 will be merged.

**Comment by billz** [comment]
Resolved by #410
