### ISSUE TITLE
No Internet with latest (1.6.2) clean installation

### ISSUE THREAD

**Issue by snIP3r23** [billz/raspap-webgui#415]
**Describe the bug**
I have a clean install of the latest version of raspap (1.6.2). everything works, but no internet of a client connected to  the ap.

**Your environment**
* Raspberry Pi Model 4
* Raspbian version: Buster Desktop  2019-09-26
* Followed the project prerequisites? (Y)
* Checked the project FAQ? (Y)
* RaspAP Quick Install or Manual setup? (Y)
* Using default configuration? (N)
* Simultaneous AP and managed mode? (Y)
* Onboard wireless chipset or external adapter? Both, onboard as a client, a tp link wn722n as the ap (driver version  v5.2.2.4_25483.20171222, /lib/modules/4.19.75-v7l+/kernel/drivers/net/wireless/8188eu.ko)
* Other software or services running with RaspAP? Standard Installation, no extra Services running

**Steps to reproduce**
Installed via quick installer, enabled simultaneous ap and wifi client, changed config like described here https://github.com/billz/raspap-webgui/wiki/FAQs#how-do-i-prepare-the-sd-card-to-connect-to-wifi-in-headless-mode to have a setup internet->wlan0 (wifi client, onboard wlan) -> wlan1 (wifi ap, tp-link usb) -> device

**Expected behavior**
client can connect to the internet

**Actual behavior**
client is connected to the ap but has no internet connection

**Additional context**
output of iptables:
pi@raspberrypi:~ $ sudo iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
MASQUERADE  all  --  anywhere             anywhere
MASQUERADE  all  --  192.168.50.0/24     !192.168.50.0/24

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

output of /etc/sysctl.conf:
net.ipv4.ip_forward=1

followed the tips here https://www.instructables.com/id/Raspberry-Pi-As-Completely-Wireless-Router/ and here https://github.com/billz/raspap-webgui/issues/141 with no success :(
i dont know what else to check, any help is very appreciated!!!

**Comment by billz** [comment]
Did you also follow these steps in the [FAQ](https://github.com/billz/raspap-webgui/wiki/FAQs#interfaces)?

**Comment by snIP3r23** [comment]
yes.
sorry, added the wrong reference in my issue.

**Comment by billz** [comment]
Bear in mind that it's impossible to test this project against all WiFi dongles on the market. Some work, others don't. 

At minimum, you will need an nl80211 compatible device and driver that supports AP mode. This can be verified with `iw list`. Search for this in the issues as it's been discussed before.

**Comment by snIP3r23** [comment]
ok got it. searched for the AP flag of the devices:
onboard:
Wiphy phy0
        max # scan SSIDs: 10
        max scan IEs length: 2048 bytes
        max # sched scan SSIDs: 16
        max # match sets: 16
        max # scan plans: 1
        max scan plan interval: 508
        max scan plan iterations: 0
        Retry short limit: 7
        Retry long limit: 4
        Coverage class: 0 (up to 0m)
        Device supports roaming.
        Supported Ciphers:
                * WEP40 (00-0f-ac:1)
                * WEP104 (00-0f-ac:5)
                * TKIP (00-0f-ac:2)
                * CCMP-128 (00-0f-ac:4)
                * CMAC (00-0f-ac:6)
        Available Antennas: TX 0 RX 0
        Supported interface modes:
                 * IBSS
                 * managed
                 * AP
                 * P2P-client
                 * P2P-GO
                 * P2P-device

and the usb device:
Wiphy phy1
        max # scan SSIDs: 9
        max scan IEs length: 2304 bytes
        max # sched scan SSIDs: 0
        max # match sets: 0
        max # scan plans: 1
        max scan plan interval: -1
        max scan plan iterations: 0
        Retry short limit: 7
        Retry long limit: 4
        Coverage class: 0 (up to 0m)
        Supported Ciphers:
                * WEP40 (00-0f-ac:1)
                * WEP104 (00-0f-ac:5)
                * TKIP (00-0f-ac:2)
                * CCMP-128 (00-0f-ac:4)
        Available Antennas: TX 0 RX 0
        Supported interface modes:
                 * IBSS
                 * managed
                 * AP
                 * P2P-client
                 * P2P-GO
so i assume the realtek rtl8188eu is capable of being an ap.
another point is, that the ap is up and running. i can connect to it with my android tablet....

**Comment by billz** [comment]
The rtl8188eu chipset is problematic in AP mode on the RPi. In the past, Realtek has maintained their own version of hostapd. You may be better off building your own hostapd per [these instructions](https://jenssegers.com/realtek-rtl8188-based-access-point-on-raspberry-pi).
