### ISSUE TITLE
Update supported translations 

### ISSUE THREAD

**Issue by billz** [billz/raspap-webgui#417]
Many new labels have been added to the project UI since the initial translation work. These must be added to the base en_US [messages.po](https://github.com/billz/raspap-webgui/blob/master/locale/en_US/LC_MESSAGES/messages.po) and pushed to the supported locales. Following that, coordinate with translators to update messages and recompile the machine object (.mo) files.

**Comment by glaszig** [comment]
i can contribute german and maybe some spanish.

**Comment by billz** [comment]
@glaszig that would be great. I've opened a PR with the updated source files. thanks!
