### ISSUE TITLE
HostAPD doesn't auto start after every boot.

### ISSUE THREAD

**Issue by krypticallusion** [billz/raspap-webgui#424]
I'm running my Raspberry Pi 3B+ with managed mode with inbuilt WiFi and AP mode enabled, however after every reboot I have to manually go to 192.168.0.48 (yes, that's what the raspAP page gets configured to) and turn on hotspot which then switches to 192.168.50.1, how I can make the reboot manual config automated?

**Comment by billz** [comment]
Please resubmit with the issue template, thanks
