### ISSUE TITLE
Does not work in client mode

### ISSUE THREAD

**Issue by Cherkes001** [billz/raspap-webgui#434]
Hi, I used raspap about a month, until yesterday, I had to re-install the raspban system, then I started to install the necessary packages, installing raspap I was in trouble, it does not work in client mode. But as an access point, raspberries are sharing the network. I apologize if the bug report was already there, I did not find it.
Raspberry Pi 4B
Buster Lite
Quick Install

![Screenshot_20191118-091959](https://user-images.githubusercontent.com/40827089/69029443-fc1ad880-09e5-11ea-8369-82196b1aa8df.jpg)
also in the screenshot you can see that there is some unknown network which has zero indicators, status, channel, etc.

**Comment by billz** [comment]
Reinitialize wpa_supplicant per [this FAQ](https://github.com/billz/raspap-webgui/wiki/FAQs#wifi-scanning-doesnt-work-help) item.

**Comment by billz** [comment]
This is not a bug with RaspAP, but it's possible the project can detect the error and reinitialize the daemon. In the meantime, you can debug and restart the daemon using the method above.
