### ISSUE TITLE
Hardcoded /home/pi paths are in mkcert.sh

### ISSUE THREAD

**Issue by ericraymond** [billz/raspap-webgui#435]
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

**Describe the bug**
I ran the cert installer script  as root.  It incorrectly tried to copy the /home/pi/.local/share/mkcert/rootCA.pem instead of the created /root/.local/share/mkcert/rootCA.pem

**Your environment**
* Raspberry Pi hardware (examples: Pi 3 Model B, Pi Zero W)  3 B+
* Raspbian version (examples: Buster Lite, Buster Desktop) Buster Lite
* Followed the project prerequisites? (Y/N) Y
* Checked the project FAQ? (Y/N) Y
* RaspAP Quick Install or Manual setup? Quick
* Using default configuration? (Y/N) Y
* Simultaneous AP and managed mode? (Y/N) Y
* Onboard wireless chipset or external adapter? Onboard 
* Other software or services running with RaspAP? VirtualHere

**Steps to reproduce**
Tell us how to reproduce this issue. Provide as much detailed information as possible.

**Expected behavior**

**Actual behavior**
Tell us what you observed instead.

**Screenshots**

**Additional context**

**Comment by billz** [comment]
Thanks for reporting
