### ISSUE TITLE
Can't perform automated install without including openvpn

### ISSUE THREAD

**Issue by ericraymond** [billz/raspap-webgui#436]
Need an install option that works with --yes that prevents installation of openvpn.

**Comment by ericraymond** [comment]
Verified!  Thank you.

**Comment by ericraymond** [comment]
Fyi might be helpful to update documentation and/or faq with an example.

Looking at the code, any value other than 1 will work. I used 0.

**Comment by billz** [comment]
Agreed. The quick installer has evolved to the stage where it could use its own dedicated wiki page.
Thanks for suggesting this change.

**Comment by billz** [comment]
https://github.com/billz/raspap-webgui/wiki/Quick-Installer-usage
