### ISSUE TITLE
Autostart Openvpn

### ISSUE THREAD

**Issue by nphawkins201** [billz/raspap-webgui#437]
Is there a way to autostart the openvpn file on startup, I can make it autostart if i move it to the /etc/openvpn folder but when i put it in the client folder it will not autostart?

**Comment by billz** [comment]
You can set the OpenVPN client to autostart at boot with `sudo systemctl enable openvpn-client@client`

This feature is currently in beta. The above will probably be added to the Quick Installer soon. Thanks for the feedback.
