### ISSUE TITLE
set wifi password to empty.

### ISSUE THREAD

**Issue by kwaknet01** [billz/raspap-webgui#439]
when i tried to change it in the raspap-gui it gives error, can i manually edit hostapd.conf and set wpa_passphrase to empty? how can i do this? i'm trying to use this with nodogsplash so that the user does not input wpa_passphrase it will automatically redirect splash.html. sorry noob here.  im just following the configuration files of nodogsplash #158 and it works!

**Comment by billz** [comment]
Great question. On the **Configure hotspot** > **Security** tab, set the Security type option to 'None'.  However, you're correct that RaspAP still enforces a wpa_passphrase. You can override this by commenting it out in `hostapd.conf`:

```
#wpa_passphrase=
```
This must be commented out or removed. Leaving it blank will cause hostapd to fail with `invalid WPA passphrase length 0 (expected 8..63)`. 

Starting hostapd from the UI will then enable a passwordless or 'unsecured' WiFi network that should work with nodogsplash as the gateway.

RaspAP should allow an empty passphrase when the no security option is selected. I'll enable this in the next update. Thanks for reporting.
