### ISSUE TITLE
WiFi clients are deauthenticating after 2 days

### ISSUE THREAD

**Issue by mister-william** [billz/raspap-webgui#440]
wlan0: STA 04:c8:07:bc:2a:87 IEEE 802.11: disassociated
wlan0: STA 04:c8:07:bc:2a:87 IEEE 802.11: disassociated
wlan0: STA 04:c8:07:bc:2a:87 IEEE 802.11: associated
wlan0: AP-STA-CONNECTED 04:c8:07:bc:2a:87
wlan0: STA 04:c8:07:bc:2a:87 RADIUS: starting accounting session 949534DBC28CAF92
wlan0: STA 04:c8:07:bc:2a:87 WPA: pairwise key handshake completed (WPA)
wlan0: STA 04:c8:07:bc:2a:87 WPA: group key handshake completed (WPA)
wlan0: STA 80:7d:3a:66:3d:5d WPA: group key handshake completed (WPA)
wlan0: STA 60:01:94:6d:f9:d2 WPA: group key handshake completed (WPA)
wlan0: STA 04:c8:07:bc:2a:87 WPA: group key handshake completed (WPA)
wlan0: AP-STA-DISCONNECTED 04:c8:07:bc:2a:87
wlan0: AP-STA-DISCONNECTED 80:7d:3a:66:3d:5d
wlan0: AP-STA-DISCONNECTED 60:01:94:6d:f9:d2
wlan0: STA 04:c8:07:bc:2a:87 IEEE 802.11: deauthenticated due to local deauth request
wlan0: STA 80:7d:3a:66:3d:5d IEEE 802.11: deauthenticated due to local deauth request
wlan0: STA 60:01:94:6d:f9:d2 IEEE 802.11: deauthenticated due to local deauth request

I am using Raspberry pi 3 model b
This is what I got from log file

**Comment by billz** [comment]
https://github.com/billz/raspap-webgui/wiki/Reporting-issues
