### ISSUE TITLE
Cannot connect to the Internet after installation on Raspberry 3 model b

### ISSUE THREAD

**Issue by HuanchengHu** [billz/raspap-webgui#442]
The board can connect to internet over WiFi before installation. After installation and reboot, it seems wifi connection function malfunctions.
My WebGUI page shows like this:

![IMG_5142](https://user-images.githubusercontent.com/32107494/69547989-5dddc400-0f4b-11ea-8077-33ceff0ce325.jpg)

When I tried to connect through Configure WiFi client tab, it shows:
![IMG_5140](https://user-images.githubusercontent.com/32107494/69547925-44d51300-0f4b-11ea-811e-125279c019a8.jpg)

When I tried to connect on raspberry configuration, it shows:
![IMG_5141](https://user-images.githubusercontent.com/32107494/69547935-4acaf400-0f4b-11ea-98f4-42837b977d0e.jpg)

Here is my wpa_supplicant.conf:
![IMG_5144](https://user-images.githubusercontent.com/32107494/69548035-7221c100-0f4b-11ea-9c78-ea1bfeb23d1f.jpg)

Anyone encountered similar issue? Thanks!

**Comment by billz** [comment]
This is covered in the FAQ https://github.com/billz/raspap-webgui/wiki/FAQs#scanning
