### ISSUE TITLE
How to use a dynamic IP Address when not in hotspot mode

### ISSUE THREAD

**Issue by delkant** [billz/raspap-webgui#45]
Hello, is there a way to use just the dynamic IP address assigned by a wifi router when the raspberry wifi is working as a client?

Thanks.

**Comment by jrmhaig** [comment]
I'll need to check that. What IP address is it using?

**Comment by delkant** [comment]
Hi @jrmhaig,  modifying  /etc/dhcpcd.conf I was able to get a dynamic IP again. 

I commented out these lines: 
#static ip_address=10.3.141.1/24
#static routers=10.3.141.1
#static domain_name_server=8.8.8.8 8.8.4.4
