### ISSUE TITLE
How to enable HTTPS?

### ISSUE THREAD

**Issue by up2smoke** [billz/raspap-webgui#451]
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

* [x] This is a bug report
* [ x] I searched existing issues before opening this one
* [ x] I checked the FAQ before creating this issue
* [ x] I have read and understand the issue reporting guidelines 

**Describe the bug**
curl -sL https://install.raspap.com | bash -s -- --cert

**Your environment**
* rPi Zero W 
* Raspbian version: Buster Lite
* Followed the project prerequisites? (Y)
* Checked the project FAQ? (Y)
* RaspAP Quick Install or Manual setup? Quick
* Using default configuration? (Y)
* Simultaneous AP and managed mode? (Cant Tell, hang on installation)
* Onboard wireless chipset or external adapter? (Both)
* Other software or services running with RaspAP? -No

**Steps to reproduce**
Fresh Install
apt update
apt upgrade
reboot
curl -sL https://install.raspap.com | bash -s -- --cert
**Expected behavior**
Use the --cert Option by a clean install

**Actual behavior**
`pi@raspberrypi:~ $ curl -sL https://install.raspap.com | bash -s -- --cert

 888888ba                              .d888888   888888ba
 88     8b                            d8     88   88     8b
a88aaaa8P' .d8888b. .d8888b. 88d888b. 88aaaaa88a a88aaaa8P
 88    8b. 88    88 Y8ooooo. 88    88 88     88   88
 88     88 88.  .88       88 88.  .88 88     88   88
 dP     dP  88888P8  88888P  88Y888P  88     88   dP
                             88
                             dP       version 2.1

The Quick Installer will guide you through a few easy steps

RaspAP Install: Configure a new SSL certificate
Current system hostname is raspberrypi
Create an SSL certificate for raspberrypi.local? (Recommended) [y/N]y
Install to lighttpd SSL directory: /etc/lighttpd/ssl? [y/N]: y
***************************************************************
A new SSL certificate for: raspberrypi.local
will be installed to lighttpd SSL directory: /etc/lighttpd/ssl
***************************************************************
Complete installation with these values? [y/N]: y
RaspAP Install: Fetching mkcert binary
RaspAP Install: Installing mkcert
Using the local CA at "/home/pi/.local/share/mkcert" ✨
RaspAP Install: Generating a new certificate for raspberrypi.local
Using the local CA at "/home/pi/.local/share/mkcert" ✨

Created a new certificate valid for the following names 📜
 - "raspberrypi.local"
 - "*.raspberrypi.local.local"
 - "raspberrypi.local"

Reminder: X.509 wildcards only go one level deep, so this won't match a.b.raspberrypi.local.local ℹ️

The certificate is at "./raspberrypi.local+2.pem" and the key at "./raspberrypi.local+2-key.pem" ✅

RaspAP Install: Combining private key and certificate
OK
RaspAP Install: Creating SLL directory for lighttpd
OK
RaspAP Install: Setting permissions and moving .pem file
OK
RaspAP Install: Configuring lighttpd for SSL
server.modules += ("mod_openssl"): Line already added
$SERVER["socket"] == ":443" {: Line already added
ssl.engine = "enable": Line already added
ssl.pemfile = "/etc/lighttpd/ssl/raspberrypi.local.pem": Line already added
ssl.ca-file = "/home/pi/.local/share/mkcert/rootCA.pem": Line already added
server.name = "raspberrypi.local": Line already added
server.document-root = "/var/www/html"}: Line already added
OK
RaspAP Install: Copying rootCA.pem to RaspAP web root
OK
RaspAP Install: Restarting lighttpd service
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor   Active: active (running) since Sun 2019-12-08 11:37:52 CET; 684ms ago  Process: 1824 ExecStartPre=/usr/sbin/lighttpd -tt -f /etc/lighttpd/lig Main PID: 1829 (lighttpd)
   Memory: 1.4M
   CGroup: /system.slice/lighttpd.service
           ├─1829 /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
           ├─1832 /bin/sh -c /usr/share/lighttpd/use-ipv6.pl 80
           └─1834 /usr/bin/perl -w /usr/share/lighttpd/use-ipv6.pl 80

Dez 08 11:37:50 raspberrypi systemd[1]: Starting Lighttpd Daemon...
Dez 08 11:37:52 raspberrypi systemd[1]: Started Lighttpd Daemon.
lines 1-13/13 (END)...skipping...
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor   Active: active (running) since Sun 2019-12-08 11:37:52 CET; 684ms ago  Process: 1824 ExecStartPre=/usr/sbin/lighttpd -tt -f /etc/lighttpd/lig Main PID: 1829 (lighttpd)
   Memory: 1.4M
   CGroup: /system.slice/lighttpd.service
           ├─1829 /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
           ├─1832 /bin/sh -c /usr/share/lighttpd/use-ipv6.pl 80
           └─1834 /usr/bin/perl -w /usr/share/lighttpd/use-ipv6.pl 80

Dez 08 11:37:50 raspberrypi systemd[1]: Starting Lighttpd Daemon...
Dez 08 11:37:52 raspberrypi systemd[1]: Started Lighttpd Daemon.
~
~
~
~`

**Screenshots**

**Additional context**
Its stucks. Nothing Happen anymore.

**Comment by billz** [comment]
Did you read the wiki? https://github.com/billz/raspap-webgui/wiki/SSL-certificates-(Quick-Installer) It's up to you to configure a client. Instructions are provided.

The output indicates that the SSL cert was created successfully, and lighttpd is configured for HTTPS.
