### ISSUE TITLE
installation script is not clear/transparent 

### ISSUE THREAD

**Issue by albjeremias** [billz/raspap-webgui#461]
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

* [ ] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**
Hei, great app, really nice stuff and very useful.. I was looking into the source code of the installation script and it's really complex and it jumps from script to script downloading scripts from the internet.. this is not very trustable in a world of spyware/adware, etc... so i'd recommend if the installation script includes the whole source code of the commands that it needs to run in a single file.. so that when you download you known exactly what the script is executing, not some arbitrary code downloaded from somewhere.

I'm not saying that your app is spyware/adware, i'm just saying that the installation script should be improved so that it is more transparent! :) maybe you don't find this important.. 

big hug.. and thank you again, for this awesome project!

**Comment by billz** [comment]
There are pros and cons to having a single monolithic install script. The installer has evolved to the stage where it can perform several functions, depending on what the user needs. As a result, it loads dependencies dynamically (currently just two files) based on runtime options. 

In terms of transparency, this is an open source project ;) 

I see your point about clarity. What might be useful is a link in the comments to each of the remote installer files. Thanks for the suggestion.
