### ISSUE TITLE
lost static IP

### ISSUE THREAD

**Issue by PA3DSS** [billz/raspap-webgui#463]
I installed raspbian lite on my RPI4 with SSH enabled, including updates and upgrade, gave it a static IP on eth0 out of the DHCP range.
After reboot i installed raspap, after install and reboot it lost the static IP, why change the static IP and  ?

**Comment by billz** [comment]
This project applies a [default configuration](https://github.com/billz/raspap-webgui/wiki/Reporting-issues#default-settings) during installation that includes a static IP address. You can modify this via the UI.
