### ISSUE TITLE
Proposed enhancement - CPU Temperature

### ISSUE THREAD

**Issue by Weylin-fr** [billz/raspap-webgui#478]
I miss the Temperature of my Raspberry, till it's closed in a case without a fan

I did'nt add the translations
see my pull request for more information

![cpu-temp](https://user-images.githubusercontent.com/6892709/72739555-22a2ee80-3ba4-11ea-99f6-c40abccfa88c.png)

**Comment by billz** [comment]
Nicely done :) I will check out your PR, thanks!

**Comment by billz** [comment]
I can see a case for having mem, cpu load & temp stats in a small widget on the dashboard. Easily done with the System class.

**Comment by Weylin-fr** [comment]
ok, why not
Do you want to do that ?

**Comment by billz** [comment]
Maybe, but after we incorporate your changes. I still think it belongs here on the System page. I made a small fix and opened a PR on your branch.

**Comment by billz** [comment]
@Weylin-fr merged with master. nice addition, thank you :)
