### ISSUE TITLE
INSTALLATION LOGIC

### ISSUE THREAD

**Issue by heraktitus** [billz/raspap-webgui#48]
NO WHERE IN THE README OR SOMEWHERE IN THE INSTALLATION DOC IT DOESN'T SAY

"CAUTION IT DELETES YOUR CURRENT /VAR/WWW/HTML/ DIRECTORY" 

Guys why remove ?

Just make a new folder under /var/www/html
B..S...

Thnks so much.

**Comment by billz** [comment]
Your files are not deleted by the installer, but rather moved to `/tmp/old_webroot`. Thanks for the constructive feedback.
