### ISSUE TITLE
2.1 regresses on 2.0

### ISSUE THREAD

**Issue by BinaryShrub** [billz/raspap-webgui#486]
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

* [x] This is a bug report
* [ ] I searched existing issues before opening this one
* [ ] I checked the FAQ before creating this issue
* [ ] I have read and understand the issue reporting guidelines 

**Describe the bug**
Client settings in 2.1 is broken for me. I see the following:
![image](https://user-images.githubusercontent.com/10691501/73294054-536acf80-4205-11ea-8ce3-060d4d45a9ae.png)

sudo git checkout tags/2.1
navigate to: http://192.168.50.1/index.php?page=wpa_conf
(gets the image above)

sudo git checkout tags/2.0
navigate to: http://192.168.50.1/index.php?page=wpa_conf
(results in a correct list of Clients)

**Comment by billz** [comment]
This occurs when `includes/config.php` is missing. Version 2.1 introduced conflict-free configuration handling 313852a698a15f82f71cbff556029ce87da7c658.

The installer or the manual setup instructions usually takes care of this. However, the wifi_stations ajax handler should fallback to the defaults. 

Thanks for reporting.
