### ISSUE TITLE
I forgot my user name and password 

### ISSUE THREAD

**Issue by toshibochan** [billz/raspap-webgui#488]
I change my password and I forgot what was. What folder and file is located user name and password?

**Comment by billz** [comment]
Login credentials are stored in `/etc/raspap/raspap.auth`. The password is encrypted and cannot be edited manually. However, you may delete this file with `sudo rm /etc/raspap/raspap.auth` and restore the default admin password.

**Comment by toshibochan** [comment]
It works thank you very much!!!
