### ISSUE TITLE
Feature request - restart hostapd

### ISSUE THREAD

**Issue by alfs** [billz/raspap-webgui#495]
Currently there is the option to 'stop hostapd', to apply new ssid settings.

But when connected via wifi, it's not possible to start it again (obviously) and the device needs a reboot or access via ethernet.

I suggest adding a button to simply restart hostapd. Preferably including a test that the config is working, to not leave the user with a broken system.

**Comment by billz** [comment]
Good suggestion.

With a managed mode AP, `sudo systemctl restart raspap.service` will indeed apply the new settings and restart the services without a reboot (tested on a Pi Zero W). Existing wifi clients will be disconnected from `uap0` but this is unavoidable. 

Re: config testing, there is already some validation that is applied to 5GHz AC. Could you be more specific on this?
