### ISSUE TITLE
Cert doesn't work on iOS 13 (catalina fine)

### ISSUE THREAD

**Issue by bmitchinson** [billz/raspap-webgui#513]
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

* [x] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**
After changing the hostname, following the quick install then cert quick install, http://{hostname}.local works but not https://{hostname}.local

**Your environment**
* Raspberry Pi hardware: (Pi 3 Model B+)  
* Raspbian version: (Buster Lite)
* Followed the project prerequisites? (Y)
* Checked the project FAQ? (Y)
* RaspAP Quick Install or Manual setup? (Quick)
* Using default configuration? (Y)
* Simultaneous AP and managed mode? (Wifi client AP Mode)
* Onboard wireless chipset or external adapter? (Onboard)
* Other software or services running with RaspAP? (None)

**Steps to reproduce**
- flashing a fresh Raspbian Buster Lite
- apt-get update, apt-get upgrade
- raspi-config to set the country code
- raspi-config to set the hostname
- `curl -sL https://install.raspap.com | bash` y to all.
- changed ssid and password
- `curl -sL https://install.raspap.com | bash -s -- --cert` y to all.
- on mac osx, installed the cert by dragging it to System and choosing Always Trust, then rebooted.
- when visiting http://{hostname.local} I get the config as expected
- when visiting https://{hostname.local}:443 I get the "your connection is not private"

**Expected behavior**
Visiting {hostname.local}:443 connects to the default config site

**Actual behavior**
Visiting {hostname.local}:443 gives  "your connection is not private".

Cert info when attempting to view https://{hostname.local}:

![image](https://user-images.githubusercontent.com/33632286/75650881-d88a3f80-5c1c-11ea-945a-fc900952efea.png)

Cert installed on mac:

![image](https://user-images.githubusercontent.com/33632286/75651015-1ab38100-5c1d-11ea-93c9-cc78ca7578d8.png)

**Comment by bmitchinson** [comment]
Does the cert fuffil the newest catalina requirements? didn't work on iOS 13 for me either?

https://superuser.com/questions/1492207/neterr-cert-revoked-in-chrome-chromium-introduced-with-macos-catalina

**Comment by bmitchinson** [comment]
I was able to follow this whack guide: https://css-tricks.com/getting-around-revoked-certificate-osx/

Which gave me a "pi@{hostname}.cer" cert? Should I serve that off the pi maybe.

**Comment by bmitchinson** [comment]
wasn't able to install that .cer on an iphone and then use it to access, but did work on the mac that made it from the "browser drag to desktop and install" trick.

**Comment by billz** [comment]
Interesting, looks like this is indeed an [issue with Catalina](https://github.com/FiloSottile/mkcert/issues/174). I ran through your steps on Mojave and got a valid cert.

![Untitled](https://user-images.githubusercontent.com/229399/75654077-2aec5000-5c5f-11ea-9c7b-52e921d6a7a3.png)

**Comment by bmitchinson** [comment]
Appreciate you looking at this so quickly! Would be curious if that is also the cause for an iPhone on iOS13? looks like it is?

**Comment by billz** [comment]
This is apparently [fixed in v.1.4.0](https://github.com/FiloSottile/mkcert/issues/174#issuecomment-522157570) of mkcert. This project uses v.1.3. I'll update the installer shortly to see if that resolves it. Thanks for reporting

**Comment by bmitchinson** [comment]
Testing now

**Comment by bmitchinson** [comment]
Worked perfectly! Closing.

**Comment by billz** [comment]
Great, glad to hear it

**Comment by bmitchinson** [comment]
Quick Installer script worked perfectly! Thanks for such a speedy fix! Looking forward to using this here: https://github.com/Haiti-Distributed-Healthcare-System/hdhs

We're early in development, but I'll be sure to discuss sponsorship once we're a bit further along! Appreciate it.

**Comment by billz** [comment]
@bmitchinson looks like an outstanding initiative! Honestly, I'd be happy just knowing some part of this project proved useful for a non-profit/humanitarian mission. Maybe down the road you'd consider sharing it on https://github.com/billz/raspap-awesome

**Comment by bmitchinson** [comment]
@billz , anyway you or anyone else could test this with an iOS device 13.3.1 (Most recent)? Still isn't working for my iPhone even though catalina is fine.

https://github.com/FiloSottile/mkcert/issues/202

**Comment by billz** [comment]
@bmitchinson followed these steps and obtained a valid cert on iOS 1.3.1 https://support.apple.com/en-nz/HT204477

![IMG_0097](https://user-images.githubusercontent.com/229399/75826223-4d898080-5da7-11ea-8adb-494ecb1e13b6.png)
![IMG_0098](https://user-images.githubusercontent.com/229399/75826225-4ebaad80-5da7-11ea-8b5b-1fed5d7c9c10.png)
![IMG_0099](https://user-images.githubusercontent.com/229399/75826226-4febda80-5da7-11ea-9ba6-f5a0a59f1bf7.png)

**Comment by bmitchinson** [comment]
Didn't know about that additional "trust cert" screen. Man that's annoyingly long to go through...
Thank you!

**Comment by billz** [comment]
It _is_ annoying... but I suppose also mirrors the rootCA trust steps on macOS
