### ISSUE TITLE
Port webgui to our board which based on i.mx6 platform

### ISSUE THREAD

**Issue by githubchenwei** [billz/raspap-webgui#520]
Thanks for your project. Now we use luci to configure the board. I want to port the webgui to our platform which is based on i.mx6. so, we just need to follow the mannual install instructions?

**Comment by billz** [comment]
That would be the place to start, yes. I'm curious to hear if you have success. Feel free to reach out via email, thanks

**Comment by billz** [comment]
Closing this as answered.
