### ISSUE TITLE
libssl1.1 : Breaks: lighttpd

### ISSUE THREAD

**Issue by DavideVito** [billz/raspap-webgui#521]
* [x] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**
I've tried to install this on my Raspberry PI 3, but I get this error:
 `libssl1.1 : Breaks: lighttpd (< 1.4.49-2) but 1.4.45-1 is to be installed`

I think that this is cased by the nginx web server I have installed on my machine, could you tell me if I'm wrong and how to fix?

**Your environment**
* Raspberry Pi 3 Model B+

**Steps to reproduce**
Run the quick installer 

**Expected behavior**
Install RaspAP

**Actual behavior**
Error during installation 
<img width="570" alt="Schermata 2020-03-08 alle 03 33 08" src="https://user-images.githubusercontent.com/47363438/76155541-8bf7a600-60ed-11ea-8006-847122c4a232.png">

**Comment by billz** [comment]
This is a [known issue](https://github.com/oerdnj/deb.sury.org/issues/995) that is not specific to RaspAP's installer. Suggest you try with a fresh SD card or `sudo apt-get install --reinstall libssl1.1`. Beyond this I can't offer troubleshooting or support.
