### ISSUE TITLE
/etc/rc.local Compatibility

### ISSUE THREAD

**Issue by gerryb** [billz/raspap-webgui#525]
Raspbian GNU/Linux 10 (buster) Raspbian GNU/Linux VERSION_ID=10 VERSION="10 (buster)"   on RasberryPi 3+

"Chown cannot access /tmp/dnsmask.log  and later /tmp/host/hostapd.log (when running it directly).   True, the files do not exist.
Fails to start /etc/rc.local  Compatability

I assume this is because /etc/rc.local is depreciated (because it is easier to use!)

**Comment by billz** [comment]
Fixed with #528. thanks @Taikuh
