### ISSUE TITLE
Use RaspAP as a access point.

### ISSUE THREAD

**Issue by Whitemanns** [billz/raspap-webgui#529]
I'm try to use the RaspAP as a access point as in

Router -Wireless- raspberry pi 3+ to Ethernet to computer but the error i get after trying is 

Configuration file: /etc/hostapd/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=eth0 disabled_11b_rates=0
nl80211 driver initialization failed.
eth0: interface state UNINITIALIZED->DISABLED
eth0: AP-DISABLED 
eth0: CTRL-EVENT-TERMINATING 

And before I'm told again to use a fresh install of the OS. Just installed a fresh VER of OS using raspberry pi imager. Raspbian lite.

**Comment by Taikuh** [comment]
I don’t entirely understand your setup. Are you trying to do what #324 is describing? Try re-describing your issue following the issue template.

**Comment by Whitemanns** [comment]
What I'd like to do instead of Wifi - Raspberry pi - Pc Wifi.
Is Wifi - Raspberry pi - Ethernet of pi out to Pc in.
If you still don't understand i can say better over a VOIP program.

**Comment by billz** [comment]
Please [read this](https://github.com/billz/raspap-webgui/wiki/Reporting-issues).
