### ISSUE TITLE
cannot access internet via RaspAP

### ISSUE THREAD

**Issue by gaurav0190** [billz/raspap-webgui#532]
hello,
i followed all the steps and installed RaspAP successfully. i log in via userid and pass.
when i enable my wifi on phone it connected and again disappear.
second i can't access internet over my Pi hotspot.
i m using Raspberry pi buster.
i tried many times . but the same thing.
anohter thing is i also can't enable wifi client AP toggle button enable

**Comment by billz** [comment]
Please [read this](https://github.com/billz/raspap-webgui/wiki/Reporting-issues), thanks
