### ISSUE TITLE
typo/update to manual installation

### ISSUE THREAD

**Issue by Zeepyro** [billz/raspap-webgui#545]
/var/www/html/installers/raspap.service 
should be 
/var/www/html/installers/raspap**d**.service

and the optional optimize php section has 7.1, should that be 7.3?

after doing those steps and manually starting httpd install was sucessful.

Thank you for your project!

**Comment by billz** [comment]
The PR was merged hours ago. A note was added to the top of the manual install steps to reflect this. I appreciate your enthusiasm, please be patient while it's updated. Thanks

**Comment by billz** [comment]
docs updated
