### ISSUE TITLE
how to update an installation

### ISSUE THREAD

**Issue by marafa** [billz/raspap-webgui#549]
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

* [x] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**

there is no documented method of updating an already running instance of raspap-webgui OR backup and reinstall

**Your environment**
* Raspberry Pi hardware (examples: Pi 3 Model B+, Pi Zero W)  
* Raspbian version (examples: Buster Lite, Buster Desktop)
* Followed the project prerequisites? (Y/N)
* Checked the project FAQ? (Y/N)
* RaspAP Quick Install or Manual setup?
* Using default configuration? (Y/N)
* Simultaneous AP and managed mode? (Y/N)
* Onboard wireless chipset or external adapter? 
* Other software or services running with RaspAP?

**Steps to reproduce**
Tell us how to reproduce this issue. Provide as much detailed information as possible.
install 
wait for an update
?

**Expected behavior**
some documentation pointing to how to update 

**Actual behavior**
Tell us what you observed instead.

**Screenshots**

**Additional context**

**Comment by billz** [comment]
> there is no documented method of updating an already running instance of raspap-webgui OR backup and reinstall

Updating is documented in the FAQ. The vast majority of the time a git pull or checkout will bring the project up to date. In rare cases, changes to the installer will need to be applied manually or require a reinstall. Breaking changes to the installer are mentioned in the release notes.

The FAQ mentions that backups are created in `/etc/raspap/backups`. Reinstallation is done by simply running the installer again. Restoring from backups is a manual process. There are no plans to automate this.

You raise a valid point re: updating. One way to improve the installer would be to add an `--upgrade` option that would skip the default configuration steps. This way, an existing installation could be safely upgraded without changing current settings.
