### ISSUE TITLE
Error when installing HTTPS support, _install_divider not found.:

### ISSUE THREAD

**Issue by arnoldandreasson** [billz/raspap-webgui#570]
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

* [x] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**
I'm trying to run "curl -sL https://install.raspap.com | bash -s -- --cert" but it ended up with this:
/tmp/raspap_mkcert.sh: line 148: _install_divider: command not found
[ ✘ error ]  Unable to install certificate 

**Your environment**
* RPi 3 B+ and RPi 4 
* Buster Lite
* Followed the project prerequisites? (Y/N) Y
* Checked the project FAQ? (Y/N) Y
* RaspAP Quick Install or Manual setup? Quick install. 
* Using default configuration? (Y/N) Y
* Simultaneous AP and managed mode? (Y/N) N
* Onboard wireless chipset or external adapter? Onboard.
* Other software or services running with RaspAP? No.

**Steps to reproduce**
1. A clean installation of Buster Lite from 2020-02-13. 
2. curl -sL https://install.raspap.com | bash
3. curl -sL https://install.raspap.com | bash -s -- --cert

**Expected behavior**
Clean installation of cert and possible to use https.

**Actual behavior**
Ended with an error message:
/tmp/raspap_mkcert.sh: line 148: _install_divider: command not found
[ ✘ error ]  Unable to install certificate 

**Screenshots**

**Additional context**
I noticed that "install_divider" recently was replaced with "_install_divider" in source code.

**Comment by billz** [comment]
Thanks for reporting
