### ISSUE TITLE
Wifi Client - connect buttons not working

### ISSUE THREAD

**Issue by zbchristian** [billz/raspap-webgui#572]
**Problem on the "Wifi client" page:**
The "connect" buttons for the available access points have no effect. Only a refresh of the page is happening.

**Three reasons:**
1) missing name="connect" tag in the corresponding `<button>` tags
  =>  `$_POST["connect"]` never set in configure_client.php
2) In configure_client.php : incorrect interface variable used in Line 19: exec('sudo wpa_cli ... select_network ...') 
 Should be RASPI_WIFI_CLIENT_INTERFACE instead of RASPI_WPA_CTRL_INTERFACE
3) In sudoer file: "wpa_cli ... select_network" not allowed due to missing [0-9]* at the end of the command

Attached a patch file.

Hope that helps!

Best
  Christian
[0001-Fixed-connect-problem-in-Wifi-Client-section.zip](https://github.com/billz/raspap-webgui/files/4557857/0001-Fixed-connect-problem-in-Wifi-Client-section.zip)

**Comment by billz** [comment]
@zbchristian thanks!
