### ISSUE TITLE
Dashboard traffic stats reported as wlan0 after changing RASPI_WIFI_CLIENT_INTERFACE

### ISSUE THREAD

**Issue by Nikotine1** [billz/raspap-webgui#577]
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

* [x] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**
Instead of eth0, I use a wifi dongle (wlx00c0ca66080c) as wifi client and wlan0 as AP. As per [this FAQ](https://github.com/billz/raspap-webgui/wiki/FAQs#interfaces), I have changed one line in config.php. However, this breaks the dashboard.

**Your environment**
* Raspberry Pi hardware: Pi 3 Model B  
* Raspbian version: Buster Lite
* Followed the project prerequisites? Y
* Checked the project FAQ? Y
* RaspAP Quick Install or Manual setup? Quick
* Using default configuration? Y
* Simultaneous AP and managed mode? Y
* Onboard wireless chipset or external adapter? both
* Other software or services running with RaspAP? no

**Steps to reproduce**
Setup an AP via wlan0.
Use external wifi dongle to connect to network, don't have ethernet connected.
Follow [this FAQ](https://github.com/billz/raspap-webgui/wiki/FAQs#interfaces) and change config.php.
From:
```
define('RASPI_WIFI_CLIENT_INTERFACE', 'wlan0');
```
To:
```
define('RASPI_WIFI_CLIENT_INTERFACE', 'wlx00c0ca66080c');
```
(Note: I have predictable network names on. Without it ```wlx00c0ca66080c``` would be called wlan1, or sometimes switch places with wlan0 during boot)

**Expected behavior**
On the dashboard you see ```wlan0 up```, the traffic via ```wlan0```, the wireless client connection for ```wlx00c0ca66080c``` and connected clients to ```wlan0```.

**Actual behavior**
The dashboard shows ```wlx00c0ca66080c up```, no connected clients and a flat traffic curve.
What does work is the wireless client box, showing the connection of ```wlx00c0ca66080c``` to the wifi router.

Traffic however is recorded for ```wlan0```, as it can be seen on the data usage page.
Also the dhcp page, client list tab is showing correctly the connected clients.

**Screenshots**
![screenshot of dashboard](https://i.imgur.com/LdoQSQv.png)

**Additional context**
N/A

**Comment by billz** [comment]
Your issue indicates AP and managed mode. In this config the virtual interface `uap0` is displayed in the status indicator, not the client interface as shown. It looks like you've configured a wireless client, but no AP. Please clarify.

**Comment by Nikotine1** [comment]
Hi @billz ,
Here are some screenshots, I hope this answers your questions.
If not, please let me know.

![1](https://i.imgur.com/PxEMReV.png)

![2](https://i.imgur.com/PSna5u9.png)

![3](https://i.imgur.com/J9RuskP.png)

**Comment by billz** [comment]
You are not in AP-STA mode. Refer to the readme on how to use this feature. 
Review our [issue policy](https://github.com/billz/raspap-webgui/wiki/Reporting-issues#issue-policy) and this statement in our FAQ:

> For these reasons, issues related to wlan0 and wlan1 configurations with external adapters will not be considered.

**Comment by Nikotine1** [comment]
No I am not, for the simple reason I want to use two different wifi devices. There's no issue with that, the access point works as intended.
I would assume it's a simple code change to show traffic and clients for the AP interface, and client details for the interface that is... the client.
But I understand you want to support this.
