### ISSUE TITLE
Wifi connection lag

### ISSUE THREAD

**Issue by fehgab** [billz/raspap-webgui#584]
Dear Developers,

Description:
I installed RaspAp software on my newly bought Raspberry Pi 4B+. I am using a class 10 micro SD card for the raspbian op.
I followed the quick installation guide and installed the software without openvpn and adBlock.
LAN internet broadcasted via Wifi AP.

Issue:
When more than one device is connected to the AP and one of these devices generate high traffic (video streaming) then on other devices network starts lagging. CPU and memory usage are never above 10-10%.

**Comment by billz** [comment]
https://github.com/billz/raspap-webgui/wiki/Reporting-issues#guidelines
