### ISSUE TITLE
NDS inactive after install

### ISSUE THREAD

**Issue by deckspace** [billz/raspap-webgui#586]
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

* [ ] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ before creating this issue
* [x] I have read and understand the issue reporting guidelines 

after clean and successful  install of RaspAP, followed the procedure to install and activate nodogsplash to add captive portal and as a result see this comment ;

pi@homunculi:/lib/systemd/system $ sudo systemctl status nodogsplash.service
● nodogsplash.service - NoDogSplash Captive Portal
   Loaded: loaded (/lib/systemd/system/nodogsplash.service; enabled; vendor pres
   Active: inactive (dead) since Tue 2020-05-12 00:16:09 BST; 3 days ago

May 12 00:16:09 homunculi systemd[1]: Starting NoDogSplash Captive Portal...
May 12 00:16:09 homunculi nodogsplash[581]: [5][Tue May 12 00:16:09 2020][581](s
May 12 00:16:09 homunculi nodogsplash[581]: [5][Tue May 12 00:16:09 2020][608](s
May 12 00:16:09 homunculi nodogsplash[581]: [3][Tue May 12 00:16:09 2020][608](s
May 12 00:16:09 homunculi nodogsplash[581]: [3][Tue May 12 00:16:09 2020][608](s
May 12 00:16:09 homunculi systemd[1]: nodogsplash.service: Succeeded.
May 12 00:16:09 homunculi systemd[1]: Started NoDogSplash Captive Portal.
lines 1-11/11 (END)

**Describe the bug**

I think as result of 'Active: inactive (dead) since Tue 2020-05-12 00:16:09 BST; 3 days ago' the day of install. Looking this up returns reference to iptables.. but am unfamiliar with this level of debugging.. please advise.

**Your environment**
* Raspberry Pi hardware  Pi 4 
* Raspbian version (Buster Desktop)
* Followed the project prerequisites? (Y)
* Checked the project FAQ? (Y/N) 
* RaspAP Quick Install ?
* Using default configuration? (Y)
* Simultaneous AP and managed mode? (Y)
* Onboard wireless chipset
* no Other software or services running with RaspAP?

**Steps to reproduce**
Tell us how to reproduce this issue. Provide as much detailed information as possible.

seems to be an issue an at the end of the install process even after reboot - raspAP looks good.

**Expected behavior**

After wireless client connection push of captive portal splash page

**Actual behavior**
Tell us what you observed instead.

Client connects through to internet gateway without intercept

**Screenshots**
see terminal capture

**Additional context**
between desk and chair!

thanks Billz, great warez

**Comment by billz** [comment]
The NDS walkthrough is provided as a courtesy only; it does not imply support of any kind by this project. Try searching issues here https://github.com/nodogsplash/nodogsplash
