### ISSUE TITLE
UI rejects entry of valid passwords for Wifi Clients

### ISSUE THREAD

**Issue by ericraymond** [billz/raspap-webgui#590]
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

* [x] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**
I entered a password of 55 characters and it was rejected?  Perhaps the quotes, spaces or other characters are expanded before processing?

**Your environment**
* Raspberry Pi hardware (examples: Pi 3 Model B+, Pi Zero W)  3B+
* Raspbian version (examples: Buster Lite, Buster Desktop)Buster Lite
* Followed the project prerequisites? (Y/N) Y 
* Checked the project FAQ? (Y/N) Y
* RaspAP Quick Install or Manual setup? Quick
* Using default configuration? (Y/N) Y 
* Simultaneous AP and managed mode? (Y/N) Y
* Onboard wireless chipset or external adapter?  Onboard wireless chipset
* Other software or services running with RaspAP?virtualhere

**Steps to reproduce**
Enter a Wifi password that is long (55 chars), has two single quotes (`),  spaces, and perhaps and exclamation mark (!)

**Expected behavior**
The password is saved and optionally used

**Actual behavior**
An error message saying the password must be between 4 and 63 characters?

**Screenshots**

**Additional context**

**Comment by ericraymond** [comment]
Just tried to reproduce this and could not.  Could be state dependent? 

I also reinstalled raspian and raspap-webgui so that may have pull different versions?

Please close.

**Comment by billz** [comment]
Unable to repro this. Closing

**Comment by ericraymond** [comment]
I think this may have been related to the issue "Fix wifi client connect button. Resolves #572"
