### ISSUE TITLE
Automatically configuring  Wifi Client and Managed Mode

### ISSUE THREAD

**Issue by ericraymond** [billz/raspap-webgui#591]
This is a feature request, not a bug report.  I assume these are encouraged.

I create my raspian image with scripts that setup raspap-webgui at first startup.  Currently I need to manually connect via a browser, make some manual changes, and then finish the setup.

Is there a way during setup to specify the Wifi Client to enable and then enable Managed AP mode?  I already have the wpa_supplicant.conf file fully populated at that point.

**Comment by billz** [comment]
[This wiki article](https://github.com/billz/raspap-webgui/wiki/RPi-Zero-W-AP-STA-mode) is relevant to your use case. Set values in `/etc/raspap/hostapd.ini` and restart the raspap daemon with `sudo systemctl restart raspapd.service`
