### ISSUE TITLE
Bridge mode - after ~10 hours wifi becomes inaccessible

### ISSUE THREAD

**Issue by tarikaltuncu** [billz/raspap-webgui#597]
I am running raspap (bridged mode) since yesterday on a clean Raspbian OS on Raspberry pi 4 with 4gb RAM.
It works well for nearly 10 hours, then wifi becomes inaccessible. All connected clients (only 3-4 devices) are frozen for a while until their connectivity drops. The signal is still available, but no device can reconnect. 
I can only open the GUI, go to Hotspot > Restart Hotspot and it starts working for another round.

**Your environment**
* Raspberry Pi hardware : Pi 4 with 4GB
* Raspbian version : Buster 
* Followed the project prerequisites? N
* Checked the project FAQ? Y
* RaspAP Quick Install or Manual setup? quick install
* Using default configuration? bridged AP mode, change of wifi and interface passwords
* Simultaneous AP and managed mode? n
* Onboard wireless chipset or external adapter?  onboard
* Other software or services running with RaspAP? clean install. nothing else then raspap yet

**Steps to reproduce**
running on bridged ap mode. No known specific reproduction steps yet, except waiting.

**Expected behavior**
it should work until it is stopped.

**Actual behavior**
Tell us what you observed instead.

**Screenshots**

**Additional context**

**Comment by billz** [comment]
Duplicate of #566
