### ISSUE TITLE
Drop Box for Countries (Contribution)

### ISSUE THREAD

**Issue by gmeter** [billz/raspap-webgui#60]
I have added a drop box for the countries and it is working fine.  Uses a javascript function to set the selected country from the php,

 Let me know if you want the code.

**Comment by jrmhaig** [comment]
Thanks. If you can submit a pull request we could have a look.

**Comment by gmeter** [comment]
I don't know how to create a pull request without a commit branch.

Code is here https://drive.google.com/file/d/0B9tW3CajMYqyNWxyMlVBamtnXzA/view?usp=sharing

**Comment by billz** [comment]
Nice addition, thanks @gmeter
