### ISSUE TITLE
Feature: External Api to manage RaspAp Configurations

### ISSUE THREAD

**Issue by fjhunter** [billz/raspap-webgui#602]
Hello everybody,

I would like to use RaspAp as Hotspot and as WLAN client for an IoT Network. 
A Server should take care of managing this network. 
So I can`t use the gui to change the RaspAp settings. I need to change them externally. It would be great to get all current settings via REST Api and be able to change them.

## What needs to be done 

* Additional Rest Endpoints which return json instead of rendered html(e.g.: get all available wifi stations).
* A [Swagger documentation](https://swagger.io/) for the REST endpoints. With which you can automatically create your REST client

**Comment by billz** [comment]
Sounds great. What can you contribute?

**Comment by fjhunter** [comment]
I started with the swagger documentation, when I noticed, that some rest endpoints are missing. I'm planning on adding the additional rest endpoints and finishing the swagger documentation in the next few weeks

**Comment by alexszilagyi** [comment]
@fjhunter : Thanks for your contribution! Could you please tell me the endpoint URL? Something like: `https://10.3.141.1/api/` ?
