### ISSUE TITLE
cannot setup raspap because of renaming interfaces

### ISSUE THREAD

**Issue by snIP3r23** [billz/raspap-webgui#603]
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

* [x] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**
trying to setup raspap with 2 wlan interfaces cannot be finished because uap0 will be renamed to rename5 and so i cannot complete my setup of raspap

**Your environment**
* Raspberry Pi hardware Pi 4 Model B
* Raspbian version Buster Lite Version 2020-05-27-raspios-buster-lite-armhf, all packages updated
* Followed the project prerequisites? Y
* Checked the project FAQ? Y
* RaspAP Quick Install or Manual setup? Quick Install
* Using default configuration? Y
* Simultaneous AP and managed mode? N
* Onboard wireless chipset or external adapter? Both, onboard and Realtek WN822n Ver. 3.0 (Kernel Module rtl8192cu)
* Other software or services running with RaspAP? N

**Steps to reproduce**
Install RaspAP like described here: https://github.com/billz/raspap-webgui
Configure WLAN: 
/etc/udev/rules.d/72-static-name.rules
ACTION=="add", SUBSYSTEM=="net", DRIVERS=="rtl8192cu", NAME="wlan0"
ACTION=="add", SUBSYSTEM=="net", DRIVERS=="brcmfmac", NAME="wlan1"
and change config in /var/www/html/includes/config.php
define('RASPI_WIFI_CLIENT_INTERFACE', 'wlan1');
this is to ensure wlan 0 is always the hotspot interface and wlan 1 the wifi client interface

in hotspot settings - advanced change wifi client ap mode ON and therefore the virtual interface uap0 will be created

**Expected behavior**
in hotspot settings - advanced change wifi client ap mode ON and therefore the virtual interface uap0 will be created and so i can setup the uap0 device for hotspot and dhcp.

**Actual behavior**
uap 0 will be created but later renamed by kernel:
[   26.249494] brcmfmac mmc1:0001:1 rename5: renamed from uap0

**Additional context**
i deactivated predictable interfaces by adding net.ifnames=0 to /boot/cmdline.txt and also tried to disable with raspi-config.
i cannot use the rename5 interface as hotspot interface nor dhcp interface.

**Comment by billz** [comment]
Similar to your previously closed issue #415. You are misusing the AP-STA mode virtual interface. This is not a troubleshooting forum.
