### ISSUE TITLE
Hotspot only accepts one connection 

### ISSUE THREAD

**Issue by robertteal** [billz/raspap-webgui#606]
This is a bug report
  I searched existing issues before opening this one
  I checked the FAQ before creating this issue
  I have read and understand the issue reporting guidelines

Describe the bug
The first connection to the hotspot connects and works without issue. Subsequent connections are refused with password error, although the correct password is stored in the client. At this point the first connection is frozen. Pi has to be rebooted to reset.

Your environment

Raspberry Pi hardware: Pi 4
Raspbian version: Raspberry Pi OS 32bit desktop downloaded 6th June.
Followed the project prerequisites? : Y
Checked the project FAQ? : Y
RaspAP Quick Install or Manual setup? : Quick install
Using default configuration? : Y
Simultaneous AP and managed mode? : Y
Onboard wireless chipset or external adapter? : Onboard
Other software or services running with RaspAP? : Fresh install
Number of users is default at 2007
Steps to reproduce
Run quick installer on raspberry pi os (may 2020) running on Pi 4. The fault was also on previous install with earlier RPi4 and Raspbian.

**Comment by billz** [comment]
The desktop version of RPi OS is unsupported.
