### ISSUE TITLE
Addition to the Network UI: Information about the current internet connectivity

### ISSUE THREAD

**Issue by zbchristian** [billz/raspap-webgui#618]
I had frequently the problem, that I wanted to know the IP address assigned to the raspi, the gateway and the connectivity of the uplink to the internet. Especially, if connectivity exists, but DNS resolution fails.
I added the corresponding information to the Network UI (see image below). the connectivity is tested via ping to the cloudfare DNS server (1.1.1.1 and one.one.one.one). 
If of general interest, I can provide a pull request.

![image](https://user-images.githubusercontent.com/33725910/85729232-e9dde700-b6f8-11ea-860e-a487578270ee.png)

**Comment by billz** [comment]
Nice work, I think others would find this useful. If you create a PR I'll give it a test. Thanks

**Comment by billz** [comment]
@zbchristian I've pushed some commits to your feature branch. give them a look, we can merge this when done.

**Comment by tped** [comment]
Very nice feature (and software, I may add!)

Mostly an FYI in case you are scratching your head on internet connectivity issues in the future ... but ...

Our ISP (TDS) blocks cloudflare 1.1.1.1!  I originally found this when Dietpi starting pinging 1.1.1.1 to test internet connectivity.   - Here's one of the articles: (https://actiontecsupport.zendesk.com/hc/en-us/community/posts/360056087832-T3200-DNS-blackholed-for-Cloudflares-1-1-1-1-and-1-0-0-1).  Actiontec/TDS issue is a looong story/debate, I simply avoid 1.1.1.1.

I changed  /var/www/html/includes/defaults.php to get it working.  Internet access works fine even though Internet Connection screen still shows 1.1.1.1/one.one.one.one with red Xs.  I can dig into that part and submit bug/change form if needed.

changed ...
'RASPI_ACCESS_CHECK_IP' => '1.1.1.1',
'RASPI_ACCESS_CHECK_DNS' => 'one.one.one.one',

to ...
 'RASPI_ACCESS_CHECK_IP' => '9.9.9.9',
  'RASPI_ACCESS_CHECK_DNS' => 'dns.quad9.net',

May help others

**Comment by frennkie** [comment]
@billz @zbchristian I really like this addition! :-D  

Would it also be possible to display the full routing table at the bottom? As far as I see it "Current settings" simply show's the standard output for each interface (ignoring the loopback) of `ip address show`. Could the output of `ip route show` be added?

**Comment by billz** [comment]
@frennkie an IP routing table is a **great** idea and would be very useful in this context.
I'll carve out some time and work on a prototype. many thanks for the suggestion.

**Comment by billz** [comment]
The **Internet connection** table also uses `ip route list` however the output is processed to render a more user-friendly summary. 

Below this, the **Routing table** section simply dumps the same command output but in a raw form. It's displayed with pre-formatted text similar to the interface details. 

<img width="512" alt="image" src="https://user-images.githubusercontent.com/229399/164397756-35e40103-c18e-41b1-a560-a1bf666b21b6.png">

@frennkie @zbchristian thoughts on this?

**Comment by frennkie** [comment]
Looks good to me..! :-) 👍
