### ISSUE TITLE
Dashboard doesn't display ESSID with special characters 

### ISSUE THREAD

**Issue by marrold** [billz/raspap-webgui#62]
The Dashboard will not display an ESSID that contains special characters.

This is caused by this line only matching alpha-numeric characters-

`preg_match( '/ESSID:\"([a-zA-Z0-9\s]+)\"/i',$strWlan0,$result );`

I suggest it's updated to-

`preg_match( '/ESSID:\".+)\"/i',$strWlan0,$result );`

**Comment by billz** [comment]
See #49
