### ISSUE TITLE
[Question] Is it normal for a Pi 3 to hit 60C at boot?

### ISSUE THREAD

**Issue by Kzitold** [billz/raspap-webgui#621]
![Screenshot_20200628-152121_VNC Viewer](https://user-images.githubusercontent.com/19679143/85956342-43d9e900-b953-11ea-97df-4dd5d8fcc465.jpg)

How is it producing so much heat?

**Comment by billz** [comment]
See [this comment](https://github.com/billz/raspap-webgui/pull/479#issuecomment-646883153). If your issue persists use the provided template.

**Comment by Kzitold** [comment]
Apparently, unplugging the HDMI drops the temp by like 20C.

My setup was going for operating the Pi strictly over **direct** VNC anyway, so I guess it's not a big deal.
