### ISSUE TITLE
Separate IoT Network without Internet Access/Router

### ISSUE THREAD

**Issue by Tscherno** [billz/raspap-webgui#626]
Hi,

I want to use RaspAP for a very special use case: I have one IoT device, which is not and should not connected to my normal network. That device (an energy meter) should have a fixed IP and connected via ethernet to the Raspi. The Raspi provides an AP with a special SSID. I connect my Phone/Laptop only to it, when needed. WIFI client needs to get an IP via DHCP from Raspi.

I tried that setup yesterday, but was not successful. I was able to connect to the Raspbi via Wifi, but never to the IoT device.

Is that in general possible with RaspAP? Do i have to do some special configuration?

Something I never understood as well: can I have the same IP range on eth0 and wlan? Something like that:

```
IoT Device                                                    Raspi                                                                  Client
==============                                 ===============                                    ===============
IP: 192.168.2.3              ::::: => eth <= :::::     eth-IP: 192.168.2.1                                            192.168.2.100-200 
static                                                             wlan-IP: 192.168.2.2       :::::: => WIFI <= ::::     DHCP-Client
==============                                 ===============                                    ===============

**Comment by billz** [comment]
Sounds like you need a different subnet for the AP side of your network. You can of course modify the [default config](https://github.com/billz/raspap-webgui/tree/master/config) to suit your needs, although this is unsupported.

Your question might fare better on the Raspberry Pi forums.
