### ISSUE TITLE
Using upgrade option breaks a few things, some due to new/changed configuration

### ISSUE THREAD

**Issue by jzr1991** [billz/raspap-webgui#629]
* [x] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**
UPGRADED to the latest version of RaspAp after installing it a few months back. The following broke:

1. **Password reset back to "secret".** Unsure about this, but seems to be to do with the expected location of RASPAP_CONFIG/raspap.auth?

2. **Branding in top left says "RASPAP_BRAND_TEXT" (or similar at least) rather than RaspAp**. This is a new configuration item it seems. I'm guessing because the upgrade doesn't overwrite config, it didn't overwrite defaults either and therefore the new keys weren't created, leading to my installation missing the config key/value for "RASPAP_BRAND_TEXT"

3. **Dashboard shows rasp_wifi_ap interface down and no graph**. Similar to above. If I look here (https://github.com/billz/raspap-webgui/commit/8ae1e5a8f271ee97bee73eeaea9b132de939c4b6) the key was changed. However, when I look at my config, it has the old value. Looks to be because the upgrade doesn't overwrite config, it also doesn't update newly named keys and therefore the code can't find the key/value and thinks it's down instead.

**Your environment**
* Raspberry Pi hardware (examples: Pi 3 Model B+, Pi Zero W): Pi 4B
* Raspbian version (examples: Buster Lite, Buster Desktop): Buster Lite
* Followed the project prerequisites? (Y/N) Y
* Checked the project FAQ? (Y/N) Y
* RaspAP Quick Install or Manual setup? Quick install, then upgrade recently.
* Using default configuration? (Y/N) Y
* Simultaneous AP and managed mode? (Y/N) N
* Onboard wireless chipset or external adapter?  Onboard
* Other software or services running with RaspAP? None

**Steps to reproduce**
Install raspap version from around March. Set up hotspot, change password.
Try upgrading. 

**Expected behavior**
Installs with no issues, everything as before.

**Actual behavior**
See bug description for 3 issues found so far.

**Additional context**

Fix for me was to update /var/www/html/includes/defaults.php

Also found these don't exist either

'RASPI_ACCESS_CHECK_IP' => '1.1.1.1',
'RASPI_ACCESS_CHECK_DNS' => 'one.one.one.one',

**Suggested fix**

I would guess updating the upgrade process to overwrite defaults.php would fix issues 2/3. As for issue 1, I'm not 100% sure,  perhaps where you previously saved the auth file has changed, and the new upgrade script checks there instead of where it used to be?

**Comment by billz** [comment]
Thanks for pointing out the auth reset. This should be handled by the installer.

Re: defaults.php, this is applied/overwritten during an upgrade, so unclear why it failed in your case. 

https://github.com/billz/raspap-webgui/blob/ec94706b321877542c44a01bea3059d649cca512/installers/common.sh#L305
