### ISSUE TITLE
Webserver not properly displayed

### ISSUE THREAD

**Issue by 3isenHeiM** [billz/raspap-webgui#630]
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

* [ ] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**
I've installed RaspAP following the quick installer.
When browsing to the homepage of the RPi, the WebUI get displayed with HTTP code.

I've tested this webpage on multiple browsers (Firefox, Chrome, etc), and it's the same behavior everywhere.

**Your environment**
* Raspberry Pi hardware : Pi 3 Model B+  
* Raspbian version : Buster Lite,
* Followed the project prerequisites? Y
* Checked the project FAQ? Y
* RaspAP Quick Install
* Using default configuration? Yes
* Simultaneous AP and managed mode? No
* Onboard wireless chipset or external adapter? Both, but built-in wifi is used.
* Other software or services running with RaspAP?

**Steps to reproduce**
Quick install of RaspAP, then browse to the homepage

**Expected behavior**
WebUI to be displayed normally.

**Actual behavior**
Content of the `index.php` file is displayed, instead of being rendered properly.

**Screenshots**

![Screenshot from 2020-07-13 11-44-37](https://user-images.githubusercontent.com/26417172/87293890-3e5bd180-c503-11ea-912d-089a57c66e9b.png)

![Screenshot from 2020-07-13 12-21-17](https://user-images.githubusercontent.com/26417172/87293968-5cc1cd00-c503-11ea-9e55-15aa7219837f.png)

**Comment by billz** [comment]
Your web service is not processing php. Do the following:

1. Run the installer again
2. Same result?
3. Repeat step 1 on a clean Buster Lite

Alternatively, refer to the php config steps in the manual setup instructions.
