### ISSUE TITLE
WiFi client AP mode greyed out with no indication of why

### ISSUE THREAD

**Issue by jasonblewis** [billz/raspap-webgui#639]
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

* [ ] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**
I want to enable the wifi client on WLAN1. From what I can tell, I need to enable WiFi client AP mode however this is greyed out.
See screenshot
![Screenshot from 2020-07-23 19-12-14](https://user-images.githubusercontent.com/129165/88270650-4db7f780-cd19-11ea-8f3e-4495ef789a42.png)

**Your environment**
* Raspberry Pi 4  
* Raspbian version Rasberry Pi OS
* Followed the project prerequisites? (Y)
* Checked the project FAQ? (Y)
* RaspAP Quick Install or Manual setup? Quick install
* Using default configuration? (Y)
* Simultaneous AP and managed mode? (Y)
* Onboard wireless chipset or external adapter? Both
* Other software or services running with RaspAP?

**Comment by billz** [comment]
> I want to enable the wifi client on WLAN1. From what I can tell, I need to enable WiFi client AP mode however this is greyed out.

The **WiFi client** UI is designed for this. AP-STA, aka wifi client AP mode is a different animal. More info [here](https://github.com/billz/raspap-webgui/wiki/FAQs#can-i-use-wlan0-and-wlan1-rather-than-eth0-for-my-ap).

**Comment by jasonblewis** [comment]
Thanks, I've tried those instructions but they didn't work for me. I'll give it a go again though. thanks for the pointer

**Comment by BinaryShrub** [comment]
I'm having the same problem, what was the fix?
