### ISSUE TITLE
CUPS Integration

### ISSUE THREAD

**Issue by Markus1995** [billz/raspap-webgui#64]
Hello,

have anyone an idea, how i can open the Cups Interface from the menu?

**Comment by jrmhaig** [comment]
I'm not sure what you are referring to. I do not think there is any link to Cups.

**Comment by Markus1995** [comment]
Ich would add a Button in the sidebar menu, that bring me to the Site of CUPS (Ip adress:631). Without a Backslash between the Ip adress and 631

**Comment by billz** [comment]
Closing this issue now, please reopen if needed.
