### ISSUE TITLE
Docker installation stops RASPAP Internet Access for Clients - FAQ Entry

### ISSUE THREAD

**Issue by svenlimbach** [billz/raspap-webgui#645]
* [x] This is an useful Information for the FAQ'S

**Describe the bug**
After installation of docker via "sudo curl -sSL https://get.docker.com | sh" the RASPAP Clients have no access to the internet anymore. By default Docker sets the policy for the FORWARD chain to DROP.

https://docs.docker.com/network/iptables/ -> Docker on a router

**Your environment**
* Raspberry Pi 4 
* Raspbian Buster Lite
* Followed the project prerequisites? Y
* Checked the project FAQ? Y
* RaspAP Quick Install or Manual setup? Quick Install
* Using default configuration? Y
* Simultaneous AP and managed mode? Y
* Onboard wireless chipset or external adapter? OnBoard
* Other software or services running with RaspAP? Docker

**Steps to reproduce**
Install Docker

**Expected behavior**
RASPAP Clients should have Internet Access after installation of docker

**Actual behavior**
Internet Access is stopped after docker installation. The following iptables Rule needed to be added to establish Internet Access for RASPAP Clients

sudo iptables -I DOCKER-USER -i src_if -o dst_if -j ACCEPT

**Comment by billz** [comment]
@svenlimbach added [this FAQ](https://github.com/billz/raspap-webgui/wiki/FAQs#what-breaks-raspap-when-docker-is-installed-on-the-same-system-and-how-i-can-fix-it). Thanks
