### ISSUE TITLE
Only a question of possibility

### ISSUE THREAD

**Issue by witteschnitte** [billz/raspap-webgui#65]
hey all,

i like this Project. ist now very simple to set the raspi Wifi.
Is there may also a possibility to set all the Network Settings including the LAN IP Address?

I´m happy to Hearing from you.
Regards
Felix

**Comment by jrmhaig** [comment]
More options could be added but to set anything that is not visible in the web interface you will need to log in and edit the configuration files yourself.

**Comment by witteschnitte** [comment]
Hi,
Tank you for your answer.
Unfortunately i do not know which configs i had to edit.
could you advice me?

Regards
