### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Alpha-1729** [billz/raspap-webgui#651]
**My environment**
* Raspberry Pi 4B 4GB RAM.  
* Raspbian version :Buster Lite
* Followed the project prerequisites? Y
* Checked the project FAQ? Y
* RaspAP Quick Install
* Using default configuration? Y
* Simultaneous AP and managed mode? (Y/N)
* Onboard wireless chipset and  external adapter? 
* Other software or services running with RaspAP? No

I have external adapter with high gain antenna. ->wlan1
onboard wireless chipset->wlan0

I need to use wlan1 for wifi client and
wlan0 for  AP.

Is it posssible.
How to set up like this.

**Comment by billz** [comment]
https://github.com/billz/raspap-webgui/wiki/FAQs#can-i-use-wlan0-and-wlan1-rather-than-eth0-for-my-ap

**Comment by Alpha-1729** [comment]
> 
> 
> https://github.com/billz/raspap-webgui/wiki/FAQs#can-i-use-wlan0-and-wlan1-rather-than-eth0-for-my-ap

I need to inverse of that case.
wlan1 as wifi client and wlan0 as AP.
