### ISSUE TITLE
After 10 devices are connected to the AP, no other device can connect

### ISSUE THREAD

**Issue by x0tester0x** [billz/raspap-webgui#657]
**Describe the bug**
After there are 10 devices connected to the AP, no other device can connect to it

**Your environment**
* Raspberry Pi hardware: Pi 3 Model B
* Raspbian version: Buster Lite
* Followed the project prerequisites? Y
* Checked the project FAQ? Y
* RaspAP Quick Install or Manual setup? Quick Install
* Using default configuration? Y(only changed SSID and PASSWORD)
* Simultaneous AP and managed mode? N
* Onboard wireless chipset or external adapter? Onboard
* Other software or services running with RaspAP? N

**Comment by billz** [comment]
Duplicate of #462. See also https://github.com/raspberrypi/linux/issues/3010
