### ISSUE TITLE
Unable to modify /etc/dnsmasq.d/090_raspap.conf for AdBlock

### ISSUE THREAD

**Issue by titithebad** [billz/raspap-webgui#658]
Hello,

During installation of RaspAb, I have this error : 
Adding blocklists to /etc/raspap/adblock
Moving and setting permissions for blocklist update script
appartenance de '/etc/raspap/adblock/domains.txt' modifiée de root:root en root:www-data
appartenance de '/etc/raspap/adblock/hostnames.txt' modifiée de root:root en root:www-data
appartenance de '/etc/raspap/adblock/update_blocklist.sh' modifiée de root:root en root:www-data
Enabling local DNS name resolution for DHCP clients
sed: impossible de lire /etc/dnsmasq.d/090_raspap.conf: Aucun fichier ou dossier de ce type
[ ✘ error ]  Unable to modify /etc/dnsmasq.d/090_raspap.conf 
Enabling ad blocking management option
[ ✓ ok ] 

Why ?

I am on Buster updated with a Rpi 3b+ !

Regards

**Comment by billz** [comment]
The error indicates that `/etc/dnsmasq.d/090_raspap.conf` does not exist, so it can't be modified. 
Either run the installer again or copy it manually with:

```
sudo cp [your install directory]/config/dnsmasq.conf /etc/dnsmasq.d/090_raspap.conf
```
