### ISSUE TITLE
"PiZero W" revision should be "9000c1" not "9000C1"

### ISSUE THREAD

**Issue by justinbarkhuff** [billz/raspap-webgui#66]
In the $revisions array in the RPiVersion() function in "includes/system.php", the key for the "PiZero W" is "9000C1", but it should be "9000c1". Well, that's the revision value for my PiZero W.

**Comment by jrmhaig** [comment]
Thanks for pointing this out. I do not have a PiZero W but I will check. What revision does it display for you?

**Comment by justinbarkhuff** [comment]
My Revision shows

`Revision	: 9000c1`

**Comment by billz** [comment]
Confirmed, appreciate this @justinbarkhuff
