### ISSUE TITLE
OpenVPN IPv4 Address Link Broken

### ISSUE THREAD

**Issue by deverox-GHT** [billz/raspap-webgui#667]
On the OpenVPN page there is a link to get you ip4 ipaddress.

Currently the link goes to: https://ipapi.co/

Which errors out.  it looks as if this link is missing info as https://ipapi.co**m**/ takes one to a whatsmyipaddress type system.  Im not sure what its supposed to be but im sure its not a link to nowhere,

**Comment by billz** [comment]
The public ipv4 link is created with the following. 

https://github.com/billz/raspap-webgui/blob/23bf46ea026b603a6aeb57bf905fda74a1542438/includes/openvpn.php#L42

Try executing this from the shell. It's possible your connection timed out.
