### ISSUE TITLE
Eth0 Static IP Configuration

### ISSUE THREAD

**Issue by robertsLando** [billz/raspap-webgui#67]
I think this is a must-have tool for every Raspberry PI. In my opinion the only thing missing is a configuration page for the eth0, it would be nice to be able to set the static IP of eth0 from this interface. What about this feature in a future release? Just need to edit the file /etc/dhcpcd.conf to configure eth0 static IP.
Let me know.

Thanks

**Comment by jrmhaig** [comment]
Thanks. This would be a useful feature and I'll give it some thought.

Unfortunately, development of new features happens when I get time and I haven't had much recently.

**Comment by billz** [comment]
There's a related request #50 for more granular control over dnsmasq settings. I'll look into combining these into a future update.

**Comment by Mark-81** [comment]
Any news about the ethernet configuration? I would fork the project if you don't plan to release the update soon. Thanks for the great job anyway!

**Comment by SirLagz** [comment]
@Mark-81 Feel free to fork it and submit a pull request to merge it back into this main branch.

**Comment by SirLagz** [comment]
Pull Request #131 addresses this issue

**Comment by billz** [comment]
@robertsLando @Mark-81 the new Configure Networking interface should allow you to do this. Closing this issue for now. Please reopen if needed, thanks.
