### ISSUE TITLE
Source for icon/logo?

### ISSUE THREAD

**Issue by rugk** [billz/raspap-webgui#670]
Do you have the source for the icon/logo somewhere?

In SVG format, I guess?

It would allow to fix further issues like #321, but also to attribute your project graphically if used in some way.

**Comment by billz** [comment]
It's SVG with some dynamically generated properties `/app/img/raspAP-logo.php`

**Comment by rugk** [comment]
Ahhh, niice indeed… Now I see. :slightly_smiling_face:
