### ISSUE TITLE
On Dashboard, SSID with imbedded blanks not displayed correctly

### ISSUE THREAD

**Issue by RobertDuncan42** [billz/raspap-webgui#674]
On the Dashboard page, in the Wireless Client information, Connect To field truncates SSID that contains blanks.

SSID I am using is "Rainbow Farms-2.4g".  Displays as "Rainbow" on the Dashboard.

Same SSID displays fine in WiFi Client page.

Noticed in RaspAP v2.5.1

My environment:

Raspberry Pi hardware: Pi 3 Model B
Raspbian version: Buster Lite
Followed the project prerequisites? Y
Checked the project FAQ? Y
RaspAP Quick Install or Manual setup? Quick Install
Using default configuration? Y(only changed SSID and PASSWORD)
Simultaneous AP and managed mode? N
Onboard wireless chipset or external adapter? Both
Other software or services running with RaspAP? N

**Comment by billz** [comment]
Resolved with #675. Thanks
