### ISSUE TITLE
Slow connection - possible to have a hotspot run through ethernet instead of wifi? (not using the onboard wifi from the raspberry pi)

### ISSUE THREAD

**Issue by ghuser030** [billz/raspap-webgui#678]
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

* [ ] This is a bug report
* [ x] I searched existing issues before opening this one
* [ x] I checked the FAQ before creating this issue
* [x ] I have read and understand the issue reporting guidelines 

**Describe the bug**
Not a bug, but how can I make a hotspot that uses ethernet instead of wifi?

**Your environment**
* Raspberry Pi hardware Pi4 - 4gb rev1.1 onboard wireless
* Raspbian version Buster Lite
* Followed the project prerequisites? Y
* Checked the project FAQ? Y
* RaspAP Manual
* Using default configuration? Y
* Simultaneous AP and managed mode? Y
* Onboard wireless chipset 
* Other software or services running with RaspAP? OpenVPN

**Steps to reproduce**
Installed OpenVPN config and my account details, made hotspot basic settings, everything is working in wi-fi mode and I see my 802.11ac 5Ghz hotspot but It doesn't run over my routers wifi but the raspberry pi wifi

**Expected behavior**
I want to be able to use the raspberry pi with raspap as a gateway to vpn, which works over wifi, but since the chip (I assume) is slow, the wifi hotspot is very slow, is there a possibility to make it so the raspberry pi with raspap only works on the software level ?

**Actual behavior**
running slow as a new wifi hotspot. i only get around 12 Mbps top speed while without the pi i have a 80-90Mbps downloadrate

**Additional context 1**
https://github.com/raspberrypi/linux/issues/2619#issuecomment-410703338
As seen on this reported issue above, I also checked my hostapd.conf. Maybe my information will help:

```
driver=nl80211
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
auth_algs=1
wpa_key_mgmt=WPA-PSK
beacon_int=100
ssid=xxxxxxxxxx
channel=44
hw_mode=a

# N
ieee80211n=1
require_ht=1
ht_capab=[MAX-AMSDU-3839][HT40+][SHORT-GI-20][SHORT-GI-40][DSSS_CCK-40]

# AC
ieee80211ac=1
require_vht=1
ieee80211d=0
ieee80211h=0
vht_capab=[MAX-AMSDU-3839][SHORT-GI-80]
vht_oper_chwidth=1
vht_oper_centr_freq_seg0_idx=42

wpa_passphrase=xxxxxxxxxxxxx
interface=wlan0
wpa=2
wpa_pairwise=CCMP
country_code=US
ignore_broadcast_ssid=0
```

**Additional context 2**
sorry for my English, its not my native language. I am using a fritzbox router and am from Germany. this is my first time using a raspberry pi and linux in general.

thank you so much for your time!

**Comment by billz** [comment]
Not exactly clear on what you're trying to achieve. This project creates a wireless AP with many router-like functions. 
If you only want your Pi to be an OpenVPN client on your network, check your existing router for an OpenVPN server option and generate an .ovpn config. If you want your Pi to act as an OpenVPN server without the AP, look at DietPi or PiVPN. Best of luck.
