### ISSUE TITLE
WiFi Client page distorted when only one SSID

### ISSUE THREAD

**Issue by RobertDuncan42** [billz/raspap-webgui#680]
* [x] This is a bug report
* [x ] I searched existing issues before opening this one
* [x ] I checked the FAQ before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**
Incorrect output on WiFi Client page when only one SSID is displayed and the screen is larger than a phone. The one displayed card is squished horizontally. Noticed this on a desktop while testing, then confirmed on a tablet, display is ok on a phone (Samsung S10+).

**Your environment**
* Raspberry Pi hardware: Pi 3 Model B+  
* Raspbian version: examples: Buster Lite
* Followed the project prerequisites? Y
* Checked the project FAQ? Y
* RaspAP Quick Install ? Y
* Using default configuration? Y
* Simultaneous AP and managed mode? N
* Onboard wireless chipset or external adapter? Alfa AWUS036NHA, RT3070 
* Other software or services running with RaspAP? N

**Steps to reproduce**
Get into a position with only one SSID in range (I removed the antenna on my dongle). Then open WiFi Client page and rescan.

**Expected behavior**
Card of the single SSID should look like it does with multiply SSID.

**Actual behavior**
The single SSID card is squished, label fields overflow and truncate.

**Screenshots**
Attached desktop screen capture.

**Additional context**
..

![RaspAP issue](https://user-images.githubusercontent.com/46305753/94018173-498e7180-fd7e-11ea-9e0b-0fd4302a1f17.gif)

**Comment by billz** [comment]
@RobertDuncan42 looks like a bug, thanks for reporting.

**Comment by billz** [comment]
<img width="689" alt="Screen Shot 2020-09-23 at 8 43 17 PM" src="https://user-images.githubusercontent.com/229399/94055581-6f972e80-fddd-11ea-8042-46a2e95b728a.png">
