### ISSUE TITLE
Feature request: Set up metric for each interface

### ISSUE THREAD

**Issue by darnokb** [billz/raspap-webgui#686]
Hi there,

I have attached to my RaspAP additional wifi dongle and LTE usb modem at the same time. When connected to wifi and lte at the same time the wifi dongle gets lower metric than lte dongle. When wifi is available nevetheless raspap uses lte dongle instead of wifi interface.
Could you implement setting up a metric into webgui?
Now I can set up metric via ssh only, it would be nice to do it via web interface.
![image](https://user-images.githubusercontent.com/18707981/94577687-229cd780-0277-11eb-8724-59c4e9c6f062.png)

**Comment by billz** [comment]
Good suggestion. This could be exposed in the Networking UI for each interface. 

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.254   0.0.0.0         UG    202    0        0 eth0
0.0.0.0         192.168.1.254   0.0.0.0         UG    303    0        0 wlan0
10.3.141.0      0.0.0.0         255.255.255.0   U     304    0        0 wlan1
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.1.0     0.0.0.0         255.255.255.0   U     202    0        0 eth0
192.168.1.0     0.0.0.0         255.255.255.0   U     303    0        0 wlan0
```
