### ISSUE TITLE
No stats while using wlan1

### ISSUE THREAD

**Issue by Ewwwer** [billz/raspap-webgui#689]
* [x] This is a bug report
* [ ] I searched existing issues before opening this one
* [ ] I checked the FAQ before creating this issue
* [ ] I have read and understand the issue reporting guidelines 

**Describe the bug**
Hi, i'm using an external wifi antenna (Realtek RTL8188EU) on Raspberry Pi 4b 4gb. 
It works fine but I have noticed that the consumption statistics are only available for eth0 and wlan0. Do I have it wrongly configured?
How can I have consumption statistics also in wlan1?
Thank you
<img width="984" alt="Captura de pantalla 2020-10-05 a las 20 17 25" src="https://user-images.githubusercontent.com/48954179/95127668-df93a600-0747-11eb-8b08-0b1454e31fb2.png">
<img width="953" alt="Captura de pantalla 2020-10-05 a las 20 17 48" src="https://user-images.githubusercontent.com/48954179/95127677-e3bfc380-0747-11eb-9a8a-85ae3761a3c1.png">
<img width="975" alt="Captura de pantalla 2020-10-05 a las 20 17 41" src="https://user-images.githubusercontent.com/48954179/95127678-e4f0f080-0747-11eb-9a75-4add30d241b3.png">

**Comment by billz** [comment]
Execute `vnstat -i wlan1` and post the result.

**Comment by Ewwwer** [comment]
Thanks @billz, the report says "unble to read database /var/lib/vnstat/wlan1: Document not found.
But the strange thing is that I was broadcasting the signal through wlan1

**Comment by billz** [comment]
The error indicates a problem with vnstat. You can try a couple of things:

1. vnstat may not be able to write to `/var/lib/vnstat`. check which user the daemon is running under with `ps aux | grep vnstatd`. if it's inactive or running under an account other than vnstat, give the service a kick with `sudo systemctl restart vnstat.service`
2. force an update for wlan1 with `sudo vnstat -u -i wlan1`. this will create the database for that interface if it doesn't exist

**Comment by Ewwwer** [comment]
Hi, I’ve tried all the possibilities that you’ve told me, this is the result: 
![1D9D47D5-17FF-45C1-B735-66DD74B37B68](https://user-images.githubusercontent.com/48954179/95247761-cd783d00-0805-11eb-9440-697e30fee879.jpeg)

But for the other way, the things are changed for the command vnstat -i wlan1: 
![3C01A786-328F-4F9C-AA59-1268547D1160](https://user-images.githubusercontent.com/48954179/95247900-03b5bc80-0806-11eb-9ef1-8c878f36728c.jpeg)

I’m gonna use it and see if your suggestions tips are working well. Thanks a lot

**Comment by Ewwwer** [comment]
Good news, it works perfectly! Thanks a lot 
![D3447708-96AA-4FE6-9C2B-69FB86D05CCB](https://user-images.githubusercontent.com/48954179/95249821-c999ea00-0808-11eb-84be-1d31362bd16d.png)

**Comment by billz** [comment]
great! glad to hear it

**Comment by brunopiras** [comment]
Same problem, but on command line appears that vnstat works, on ubuntu 20.04 (not raspberry):

apu2@routerx:~$ ps aux | grep vnstatd
vnstat      1138  0.0  0.0   5608  3768 ?        Ss   13:58   0:02 /usr/sbin/vnstatd -n
apu2        3848  0.0  0.0  11084   728 pts/1    S+   16:16   0:00 grep --color=auto vnstatd

vnstat -i wlp4s0
Database updated: 2020-10-16 16:15:00

   wlp4s0 since 2020-10-15

          rx:  64,05 MB      tx:  496,57 MB      total:  560,62 MB

   monthly
                     rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
       2020-10      64,05 MB |   496,57 MB |   560,62 MB |    3,31 kbit/s
     ------------------------+-------------+-------------+---------------
     estimated     125,88 MB |   980,29 MB |     1,11 GB |

   daily
                     rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
     yesterday      31,37 MB |   260,08 MB |   291,44 MB |   26,98 kbit/s
         today      32,68 MB |   236,49 MB |   269,17 MB |   36,81 kbit/s
     ------------------------+-------------+-------------+---------------
     estimated      48,26 MB |   349,28 MB |   397,54 MB |

![wlp4s0](https://user-images.githubusercontent.com/55226575/96271039-b20eee00-0fcc-11eb-8626-44288b7df402.png)

**Comment by billz** [comment]
@brunopiras Ubuntu 20.04 is untested and unsupported at this time.

**Comment by brunopiras** [comment]
> @brunopiras Ubuntu 20.04 is untested and unsupported at this time.

Thanks for your reply
I would like to help with this problem, the new version of vnstat generates in the /var/lib/vnstat folder a single database with the name "vnstat.db" that contains all the information about the network interfaces while, the old versions of vnstat generated a database for each interface that was detected with the name of the interface itself.

I solved this by uninstalling version 2.2.x of vnstat:

sudo apt-get purge vnstat 

 download and installing an old one (I used the 1.14):

sudo dpkg -i vnstat_1.14-1ubuntu2_amd64.deb

then blacklisting the program to avoid future updates:

echo "vnstat hold" | sudo dpkg --set-selections

Now works well..
Thanks

![vnstat](https://user-images.githubusercontent.com/55226575/96364688-24521080-113c-11eb-9435-a1c275299ee4.png)
