### ISSUE TITLE
Documentation not clear. 

### ISSUE THREAD

**Issue by pquodling** [billz/raspap-webgui#691]
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

* [ ] This is a bug report
* [ ] I searched existing issues before opening this one
* [x ] I checked the FAQ before creating this issue
* [ ] I have read and understand the issue reporting guidelines 

**Describe the bug**
Not so much a bug but an understanding of the install process.

**Your environment**
* Raspberry Pi hardware -  Pi Zero W
* Raspbian version Buster Lite
* Followed the project prerequisites? Y
* Checked the project FAQ? T
* RaspAP Quick Install or Manual setup? n/a
* Using default configuration? (Y/N)
* Simultaneous AP and managed mode? (Y)
* Onboard wireless chipset or external adapter? Onboard
* Other software or services running with RaspAP?

**Steps to reproduce**
n/a 

**Expected behavior**

**Actual behavior**
Tell us what you observed instead.

**Screenshots**

**Additional context**

Not so much a bug but not clear on how it works/best approach. 

(Posted in the subreddit a few days ago, but no response) 

I am wanting to set up a Raspberry Pi Zero W as a Raspap to use as a "Travel Router". I presume a) that I should set up my hostname ID before doing the install so that the mkcert picks up the ID etc from the hostname. .

Second question - the use of "curl -sL https://install.raspap.com | bash -s -- etc" 

can/should I stack the arguments here clearly the "-y" and the "--repo" and the "--branch" are "universal" to select where it's coming from - do I "bash -s -- -a -o -c -y -r repu/details"

or is better to do a full

curl -sL https://install.raspap.com | bash -s -- --cert " and then a

curl -sL https://install.raspap.com | bash -s -- --adblock" etc for openvpn as well.

and if so, is order important (I was thiningk that Certs will be needed before openvpn

**Comment by billz** [comment]
> I presume a) that I should set up my hostname ID before doing the install so that the mkcert picks up the ID etc from the hostname

only necessary if you want something other than raspberrypi.local. see [this wiki](https://github.com/billz/raspap-webgui/wiki/SSL-certificates-(Quick-Installer))

> can/should I stack the arguments here

all the installer arguments stack with the exception of `-c --cert` which is standalone. also discussed [in the wiki](https://github.com/billz/raspap-webgui/wiki/Quick-Installer-usage) 

> -c, --cert, --certificate
This option installs an SSL certificate with mkcert and configures lighttpd for HTTPS support. It does not (re)install RaspAP. Details are provided here.

>  is order important (I was thiningk that Certs will be needed before openvpn

the SSL certs are independent of openvpn's certs, so order is unimportant

**Comment by pquodling** [comment]
Went through everything - got to it showing an AP, etc. but no upstream internet connection - followed the instructions suggested for that in other bug reports, didn't fix it, infact It doesn't show up my LAN, or even present an AP now. Time to restart the whole process all over again. For about the fourth time.

**Comment by billz** [comment]
If not done so, check the wiki page dedicated to the Pi Zero W.

Be sure to follow the project prerequisites and use an official 5.1V power supply. If you still have issues, start with a base install, obtain a stable AP, then configure OpenVPN, SSL, etc.

There are many blog posts and project walkthroughs using RaspAP for travel router type applications. See also this repo for some detailed working examples https://github.com/billz/raspap-awesome
