### ISSUE TITLE
An AP hotspot cannot be created

### ISSUE THREAD

**Issue by 1399568389** [billz/raspap-webgui#695]
Input the curl - sL https://install.raspap.com | bash this instruction without feedback,There will be no feedback。
Execution of wget-q https://git.io/voeuq-o/TMP /raspap && bash/TMP/Raspap did not react。

**Comment by billz** [comment]
`curl -sL https://install.raspap.com | bash`

**Comment by 1399568389** [comment]
It was executed and still no response
