### ISSUE TITLE
Can connect to raspberry pi through hostap

### ISSUE THREAD

**Issue by peylight** [billz/raspap-webgui#699]
Hi,
I enable Bridged AP mode and set static ip address to my raspberry pi for br0 in dhcpcd.conf but when i try to connect to the raspberry pi from wifi ap it is not possible.
I can only connect (ssh connection or ping) to raspberry pi from other side (lan connection only, not wifi ap).

**Comment by billz** [comment]
Please review our [issue policy](https://github.com/billz/raspap-webgui/wiki/Reporting-issues#issue-policy).
