### ISSUE TITLE
DHCP not working

### ISSUE THREAD

**Issue by TimyIsCool** [billz/raspap-webgui#705]
My DHCP thing is not working, i dont know why. i installed raspAP then i tryed to connect on my phone and it said 'couldn't get ip adress' I tryed reinstalling it but i still dosent work. I try start DHCP but it says 'Failed to start dnsmasq' please help.

Edit: btw i want to run a private with no public internet

regards,
Timy

**Comment by billz** [comment]
https://github.com/billz/raspap-webgui/wiki/Reporting-issues

**Comment by TimyIsCool** [comment]
? what, i dont understand?
