### ISSUE TITLE
Connection with network instable - Bridge configuration

### ISSUE THREAD

**Issue by yougospam** [billz/raspap-webgui#711]
Hello

Thank you for your job.
I need some help to understand my problem.

I installed RaspAP on my raspberry pi 3b+ and it was working.
I activated bridge option, since, i have some problem.
Sometimes, my rpi can see the network (with a ping on my router 192.168.1.1), sometimes it can't.

For example, this morning, it was working.
But now after a reboot, it doesn't work.
When i use "ip a", i see some differences on eth0, i have no inet6 and i see "master br0 state DOWN" and NO-CARRIER

Case "OK" ;
![ip_a_OK](https://user-images.githubusercontent.com/70427451/98778677-ff775300-23f2-11eb-8180-121dd8635ff8.JPG)

Case "KO" :
![ip_a_KO](https://user-images.githubusercontent.com/70427451/98778687-030ada00-23f3-11eb-871d-ea30c48d487b.JPG)

I tried a lot of things and now i'm lost.
Thank you for your help.

yougo

**Comment by billz** [comment]
https://github.com/billz/raspap-webgui/wiki/Reporting-issues
