### ISSUE TITLE
Connection with network instable - Bridge configuration

### ISSUE THREAD

**Issue by yougospam** [billz/raspap-webgui#712]
Hello

Thank you for your job and sorry for my first invalid issue (i hope this one is valid).
I need some help to understand and fix my problem.

* [x] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**
Sometimes, my rpi can see the network and get an ip (from my router 192.168.1.1), sometimes it can't.

**Your environment**
* Raspberry Pi hardware :  Pi 3 Model B+
* Raspbian version : Raspbian GNU/Linux 10 (buster)
* Followed the project prerequisites : Y
* Checked the project FAQ : Y
* RaspAP Quick Install or Manual setup : Quick install
* Using default configuration : Y
* Simultaneous AP and managed mode : N
* Onboard wireless chipset or external adapter : onboard
* Other software or services running with RaspAP : jeedom

**Steps to reproduce**
I don't really understand my problem.
I installed RaspAP on my raspberry pi 3b+ and it was working.
I activated bridge option, since, i have some problem.
Sometimes, my rpi can see the network (with a ping on my router 192.168.1.1), sometimes it can't.

For example, this morning, it was working.
But now after a reboot, it doesn't work.
When i use "ip a", i see some differences on eth0, i have no inet6 and i see "master br0 state DOWN" and NO-CARRIER

**Expected behavior**
I want to ping my router and have internet on my raspberry pi all the time

**Actual behavior**
Sometimes, i have connection with network, sometimes i have not

**Screenshots**
When i use "ip a", i see some differences on eth0, i have no inet6 and i see "master br0 state DOWN" and NO-CARRIER

When it works :
"ip a" result : 
![ip_OK](https://user-images.githubusercontent.com/70427451/98798251-f647af80-240d-11eb-95ad-3ca410a34ee0.JPG)

"dhclient -v" result :
![dhclient_OK](https://user-images.githubusercontent.com/70427451/98798225-eb8d1a80-240d-11eb-9e0b-d0afbaa9383e.JPG)

When it doesn't work :
"ip a" result : 
![ip_KO](https://user-images.githubusercontent.com/70427451/98798260-f9db3680-240d-11eb-9f71-a36601cc0ec2.JPG)

"dhclient -v" result :
![dhclient_KO](https://user-images.githubusercontent.com/70427451/98798314-09f31600-240e-11eb-9d3c-0b8cc3c9a4ce.JPG)

**Additional context**
I checked #141 #566 and #693 
I tried to fix my ip address on br0  in dhcpcd.conf and it changed nothing.

Thank you for your help.
yougo

**Comment by billz** [comment]
The RPi (client) `DHCPDISCOVER` broadcast appears normal, but there is no `DHCPOFFER` response from your router in the second output. 

If it happens intermittently, this could indicate an undervoltage issue with your RPi. Check the kernel log for any `Under-voltage detected` errors. Be sure you are using an official 5.1V power supply (each model has different power requirements) and detach any USB devices. `dmesg | grep br0` can also offer clues.
