### ISSUE TITLE
Failed at removing , and trying to find a solution without accessing the headless rpi (no eth no ssh)

### ISSUE THREAD

**Issue by boboyoyo7** [billz/raspap-webgui#719]
Model : 
Raspberry Pi 3

My situation :
I want to make my rpi work as a repeater. At first, the connection to my main router was working fine and rpi could connect to the Internet. But the thing is that when I tried to make the hotspot, I messed up and It wasn't working fine . And the big problem is that I couldn't even reconnect to my Wi-Fi from the rpi and so I lost access to my headless rpi because I  could only access it by SSH. 
So I tried your uninstall script but I failed badly this time not me but the script. At each remove command, the script stopped claiming that there were no such file or directory ... While the file was bel et bien there. 
So I fixed the problem, by chmod 777 of all files directory supposed to be removed, and did the uninstallation manually, but unfortunately the uninstalling didn't work cause I can still see the hotspot raspbwebgui . 
Now I'm asking for your help and it's quite urgent I lost plenty of time at the uninstalling and fixing to default, and it's supposed to be a school assignment I'm very late .

So, what I intend to do and I ask you if it possible : 
* Can I re-install raspap directly in the sd card , cause I have a headless raspberry and I can't access to Wifi as I stated since the raspap is installed?
* How can I remove raspap once at all? and How can I be sure that It's well removed .
* Can I reset the networking settings to default from sd card, so I can reconnect to my wifi ?
* Another solution? just to avoid resetting my rpi because I started thinking seriously 
at it.

Thank you,

**Comment by billz** [comment]
https://github.com/billz/raspap-webgui/wiki/Reporting-issues
