### ISSUE TITLE
Enhancement: File Manager

### ISSUE THREAD

**Issue by CrashPlayer** [billz/raspap-webgui#727]
Some kind of File Manager like this:
![Screenshot_2020-12-06 RaspAP WiFi Configuration Portal](https://user-images.githubusercontent.com/42744253/101283951-e12c2980-37dd-11eb-83e8-07c6713aec79.png)
In this example I used the open source [tinyfilemanager](https://github.com/prasathmani/tinyfilemanager)
I can't provide any source code because my version is more of an iframe action workaround.

**Comment by billz** [comment]
What problem is this attempting to solve?

**Comment by billz** [comment]
Please post this over in Discussions, thanks
