### ISSUE TITLE
bridged ap mode - assignment of MAC or IP to br0

### ISSUE THREAD

**Issue by presskopf** [billz/raspap-webgui#728]
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

* [x] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**

Hi!
first of all, I'd like to say thank you for this great software!

To be honest, I think this is rather a feature  request or a unknown configuration modification than a bug:
I want to expand my current network by using the "bridged AP mode" setting and letting my router doing the DHCP work.
For that I have dynamic dhcp ip address assignment based on the mac address of the clients.

Without raspap or raspap with dhcp mode this works as expected. The eth0 of the raspberry gets his IP, which is configured in the router.
By switching on AP in bridged mode, things are different. A new device br0 is defined by raspap. And this devices asks for the IP from the DHCP. It gets on, but of course it is another one than the IP of eth0.

Is it possible to assign to br0 the same MAC as eth0?
Or is it possible to assign to br0 a distinct MAC and where and how is it done?

The target is to make sure that the ethernet IP is a certain one, which is defined in the DHCP.

**Your environment**
* Raspberry Pi hardware (examples: Pi 3 Model B+)  
* Raspbian version (examples: Buster Lite)
* Followed the project prerequisites? (Y)
* Checked the project FAQ? (Y)
* RaspAP Quick Install or Manual setup? Quick
* Using default configuration? (Y)
* Simultaneous AP and managed mode? (Y/N)
* Onboard wireless chipset or external adapter? onboard
* Other software or services running with RaspAP? Y (owncloud, octoprint)

**Steps to reproduce**
can be reproduced by switching on/off bridged ap mode

**Expected behavior**
see above

**Actual behavior**
see above

**Screenshots**

**Additional context**

**Comment by billz** [comment]
Please post this over in [Discussions](https://github.com/billz/raspap-webgui/discussions), thanks.
