### ISSUE TITLE
Putty Freezes at Adding rule: -t nat -A POSTROUTING -j MASQUERADE

### ISSUE THREAD

**Issue by myxxmikeyxx** [billz/raspap-webgui#757]
I have tried doing it locally on the pi and through SSH over putty on my separate USB Wi-Fi antenna's IP address but it still freezes at that point. 
for Putty it freezes and then says connection lost and when I reconnect and see if any process are running the pi doesn't show anything running. 
If I open the website from the SSH IP it shows that the hotspot is active but it is not showing up on any of my devices.
![Problem](https://user-images.githubusercontent.com/1766849/104261395-7365c400-5453-11eb-85ed-bb58a5e62197.PNG)

**Comment by billz** [comment]
Your SSH session was interrupted. Search for 'ssh connection dropped' etc. Then re-run the installer.
