### ISSUE TITLE
wpa_supplicant.conf fills up with multiple entries of the same ssid

### ISSUE THREAD

**Issue by andyjbm** [billz/raspap-webgui#76]
In includes/configure_client.php, if the update button is pressed of an SSID that has already been configured, the wpa_supplicant.conf is not written correctly and for a set up with half a dozen ssids listed the .conf file gets rather large rather quickly with multiple duplicate entries of all the ssid configs.

The code:

          if (strlen($network['passphrase']) >=8 && strlen($network['passphrase']) <= 63) {
            exec( 'wpa_passphrase '.escapeshellarg($ssid). ' ' . escapeshellarg($network['passphrase']),$wpa_passphrase );
            foreach($wpa_passphrase as $pline) {
              fwrite($wpa_file, $pline.PHP_EOL);
            }
`

does not enumerate correctly as $line is still set from the previous pass and so the foreach writes out all the previous lines in addition to those returned on this execution of exec('wpa_passphrase....

Suggest changing to:

          if (strlen($network['passphrase']) >=8 && strlen($network['passphrase']) <= 63) {
             unset($wpa_passphrase);
             unset($pline);
             exec( 'wpa_passphrase '.escapeshellarg($ssid). ' ' . escapeshellarg($network['passphrase']),$wpa_passphrase );
             foreach($wpa_passphrase as $pline) {
               fwrite($wpa_file, $pline.PHP_EOL);
            }
`
which fixed it for me.

I changed the $line variable to $pline to remove confusion from the use of $line higher up the code.
I suspect the unset(wpa_passphrase); line is not needed but once I got it working it was time to go home...

Andy.

**Comment by billz** [comment]
Much appreciated @andyjbm, will have a look and incorporate this fix soon.
