### ISSUE TITLE
OpenVPN Config with Passphrase

### ISSUE THREAD

**Issue by githubtobi** [billz/raspap-webgui#775]
* [X] This is a bug report
* [x] I searched existing issues before opening this one
* [X] I checked the FAQ and Wiki before creating this issue
* [X] I have read and understand the issue reporting guidelines 

**Describe the bug**
OpenVPN is not connecting but a message appears in the terminal : "Password entry required for 'Enter Private Key Password:' (PID 1950). Please enter password with the systemd-tty-ask-password-agent tool:"

**Your environment**
* Raspberry Pi 3 Model B+
* RPi OS Lite
* RaspAP version 2.52
* RaspAP Quick Install
* Using default configuration? Y
* Onboard wireless chipset or external adapter? WLAN0 (internal) as Client, WLAN1 (USB Stick) as Hotspot (works fine)

**Steps to reproduce**
- clean install
- added openvpn config file
- added openvpn phrase.txt file (just one line: the passphrase)
- clicked the "start openvpn" button

**Expected behavior**
- openvpn to add TUN0 interface and establish the connection

**Actual behavior**
- openvpn is asking for the password via the command line. but even after entering the passphrase, openvpn is not connecting

**Additional Info**
I might found an answer here but I am not advanced enough to check/fix it: https://forums.openvpn.net/viewtopic.php?t=30336

**Journal Log:**
Jan 20 17:40:44 raspap openvpn[1189]: Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Jan 20 17:40:44 raspap openvpn[1189]: Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Jan 20 17:40:44 raspap openvpn[1189]: Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Jan 20 17:40:44 raspap openvpn[1189]: Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Jan 20 17:40:44 raspap openvpn[1189]: TCP/UDP: Preserving recently used remote address: [AF_INET]XXX:YYY
Jan 20 17:40:44 raspap openvpn[1189]: Socket Buffers: R=[131072->131072] S=[16384->16384]
Jan 20 17:40:44 raspap openvpn[1189]: Attempting to establish TCP connection with [AF_INET]XXX:YYY [nonblock]

-> now the broadcast message appears 

	Password entry required for 'Enter Private Key Password:' (PID 1221).
	Please enter password with the systemd-tty-ask-password-agent tool:

After I have entered the passphrase journal shows the following:

Jan 20 17:40:48 raspap openvpn[1189]: TCP: connect to [AF_INET]XXX:YYY failed: No route to host
Jan 20 17:40:48 raspap openvpn[1189]: SIGUSR1[connection failed(soft),init_instance] received, process restarting

**Openvpn Config File**
client
dev tun
proto tcp
remote <hostname> <port>
resolv-retry infinite
nobind
remote-cert-tls server
tls-version-min 1.2
verify-x509-name XXX name
cipher AES-256-CBC
auth SHA256
auth-nocache
verb 3
redirect-gateway def1
askpass /etc/openvpn/phrase.txt
+certificate information (ca, cert, key, tls-crypt)

**Comment by billz** [comment]
> OpenVPN is not connecting but a message appears in the terminal : "Password entry required for 'Enter Private Key Password:'

This is expected from your config. From the openvpn man page:

> For  the  extremely  security  conscious, it is possible to protect your private key with a password.  Of course this means that every time the OpenVPN daemon is started you must be there to type the password.  The --askpass option allows you to start OpenVPN from the command line. It will query you for a password before it daemonizes.  

Storing your password in a file invalidates the extra security of an encrypted private key, so it is not implemented in this project. If this is your own VPN server, reconfigure it to use the `--auth-user-pass` option instead of `--askpass`.

**Comment by githubtobi** [comment]
thank you. solved!
