### ISSUE TITLE
raspap-webgui & pi-hole

### ISSUE THREAD

**Issue by peylight** [billz/raspap-webgui#81]
Hi
Is it possible to install [raspap-webgui](https://github.com/billz/raspap-webgui) and [pi-hole](https://github.com/pi-hole/pi-hole) together?

**Comment by billz** [comment]
I haven't done any testing with these two projects. Suggest you check the pi-hole forum, I recall there being a discussion about RaspAP.

**Comment by YannBrrd** [comment]
Hey,

Any success on this ? I'm also really interested.

Regards

**Comment by billz** [comment]
@YannBrrd you are welcome to open a pull request and contribute to the project :)
