### ISSUE TITLE
integrate with external freeradius

### ISSUE THREAD

**Issue by t-sharabi** [billz/raspap-webgui#82]
Hello @billz 
thank you for the information posted by you, I was wondering if you can help me to add integration with external RADIUS through adding a new tab or link inside the raspap-webgui

appreciate the help

thank you

**Comment by billz** [comment]
@t-sharabi adding a tab to raspap-webgui is fairly trivial. You could, for example, rename `RASPI_TORPROXY_ENABLED` to `RASPI_RADIUS_ENABLED` in index.php and simply edit this tab to point to your integration.
