### ISSUE TITLE
WPA Client Feature Requests

### ISSUE THREAD

**Issue by zbourdeau** [billz/raspap-webgui#86]
I would like to request a couple Wifi client features.

The first one is the ability to add in additional info in the wpa_supplicant configurations network stanza's such as:
bgscan="simple:30:-65:120"

Perhaps a background scan check box on the UI would help enable this? This helps when connected to areas where multiple AP's exist with the same SSID.

It would also be great to add in the ability to select priority of WIFI through UI. In the network stanza this looks like:
priority=100
Where the higher the priority equates to a more desirable AP.

**Comment by billz** [comment]
Added to the todo list. Closing this for now, thanks
