### ISSUE TITLE
if possible to run `raspap` in docker? 

### ISSUE THREAD

**Issue by yangxuan8282** [billz/raspap-webgui#87]
It works pretty well on host, so I wonder if possible to put it in container.
I write a Dockerfile, but not work properly, it did create AP, but the client can't get IP address, and here is the logs:

```
...
ap_1  | cat: /etc/wpa_supplicant/wpa_supplicant.conf: No such file or directory
ap_1  | Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory
ap_1  | Failed to connect to non-global ctrl_ifname: (null)  error: No such file or directory
```

I have installed `wpasupplicant`, but seems it didn't generate wpa_supplicant.conf

 and running in docker is kind of different than on host, I have to manually start `hostapd` and `dnsmasq` with:  

```
/etc/init.d/hostapd start
/etc/init.d/dnsmasq start
```

I'm not sure if I have missed anything.

**Comment by billz** [comment]
Running RaspAP in a Docker container is outside the scope of this project.
