### ISSUE TITLE
Can RaspAP be used for headless bootstrapping of Wifi?

### ISSUE THREAD

**Issue by bluephlame** [billz/raspap-webgui#91]
Hi, I"m looking for a way to configure a Pi to connect to a wifi network in a headless way Can RaspAp support this? Or can it be easily adjusted to support this?

The process would be
- boot up the Pi, 
- it cannot connect to an existing wifi configuration (or doesn't have a configuration).
- Turn on the Acces point mode.
- Configure the Wifi Credentials for a local WiFi network.
- Reboot and connect to the wifi network (Acces point mode is switched off).

Thanks!

**Comment by jspraul** [comment]
#77

**Comment by SirLagz** [comment]
Yes, that is possible, but not yet implemented.
You could potentially implement it yourself with this script - http://sirlagz.net/2013/01/22/script-starting-hostapd-when-wifi-goes-down/

**Comment by billz** [comment]
Added to the todo list. Closing this for now, thanks
