### ISSUE TITLE
Dashboard don't show status about raspberry pi

### ISSUE THREAD

**Issue by mickaeldias** [billz/raspap-webgui#92]
So RaspAP have a good interface, very nice, but the dashboard don't work correctly, so take a look: http://imgur.com/lDRfMFn, and the interface don't support VPN, Bridge mode, QoS, Radius Server and etc...

**Comment by billz** [comment]
@mickaeldias VPN, Bridge mode, QoS and other non-standard configurations aren't currently supported, so what you're seeing in the dashboard is expected. These features require new UIs to administer and are on the todo list.
