### ISSUE TITLE
Use wifi dongle instead of wlan0 for better speed

### ISSUE THREAD

**Issue by Owiowi** [billz/raspap-webgui#94]
Hi,

First of all I'd like to thank you for this amazing script. I've been playing around with a lot of other scripts before being finally able to run a raspberry pi 3 hotspot running all traffic through a VPN.
I'm no expert but as far as I understand, the script uses eth0 to receive the internet connection while it shares it through the inboard wifi card (assuming we're using a raspberry pi 3).
I've done some research and found out that the speed of the inboard card is quite limited (20mbs) compared to other wifi dongles. I personally own a Ralink RT5370 WiFi Dongle (150mbs) and I was hopping to use it instead of wlan0 to share the internet connection.

Note that I'm a bit confused about the hotspot and DHCP interfaces setting on the the webpage. I played with them but I had no success, so I assumed the script couldn't do what I was looking for.
I don't know if this could be related but the dashboard doesn't give any information, it's blank. The only thing I can see is "interface: wlan0".

Therefore, I assumed this wasn't the problem and I've been trying to replace wlan0, everywhere in the script, with the name of my dongle found with ifconfig (in my case wlx48022a345156). It didn't quite work. I could see it on the dashboard and all but it doesn't start nor does it seem to take into account any change I may apply (only on dashboard & DHCP setting tabs)

I was hopping you would have an easy way to do that or perhaps add a multi interfaces feature as I saw it generated multiple interests from other users even though it was mainly for double wifi interfaces.

Please note that I've very little knowledge but I'm hopping to learn here, thanks in advance!

UPDATE: I tried to tackle the problem the other way around by renaming wlan0 to wlan 1 & wlan1 to wlan0. I rebooted, typed ifconfig and the wifi dongle was wlan0. I ran the install script but somehow it still uses the inboard wifi to share the internet connection. Any idea?

UPDATE 2: I tried to go around the original problem by fully disable the onboard wifi of RPI 3. The script runs without error and seem to install properly, though the wlan0 interface is always down. And when I tried to turn it up manually, it says "unknown interface"

UPDATE 3: I've been able to to share the ethernet connection via the wifi dongle by using the script and some manual commands but the speed has only improved from 20 mbs to 25 mbs... I assume the raspberry pi is simply not powerful enough to broadcast more? 

How I did it?
I disabled the onboard wifi by editing the file /etc/modprobe.d/disable_rpi3_wifi_bt.conf and adding the following lines: 
```
blacklist brcmfmac
blacklist brcmutil
```
Then rebooted the the rpi. 
Note: I used an older release of raspian jessie (non-stretch) as it solved a bunch of problems I had when it came to editing manually hostapd.

Hope this can help someone attempting to do the same thing I did.

**Comment by billz** [comment]
This is covered in the [FAQ](https://github.com/billz/raspap-webgui/wiki/FAQs#interfaces).
