### ISSUE TITLE
FLUCTUATING FROM AP TO CLIENT MODE

### ISSUE THREAD

**Issue by akshaykulkarni46** [billz/raspap-webgui#99]
I tried running the package in my RPi-3 and was able to Create an AP using which i tried to configure my RPi Wifi and after Adding my credentials the Wifi starts fluctuating

**Comment by billz** [comment]
@akshaykulkarni46 did you use the Quick Installer, follow the steps in the manual setup or install RaspAP on top of a custom configuration? I will gladly address _specific_ issues about RaspAP but cannot field general troubleshooting requests.

**Comment by akshaykulkarni46** [comment]
Yes I have followed all the steps given . I will try with the fresh image and let u know
